### ISSUE TITLE
How do you transform Token to string in the tree ?

### ISSUE THREAD

**Issue by vsraptor** [erezsh/lark#107]
For tokens i get : 

Token(ATOM, 'test')

in the tree. I want to get just : 

  'test'

i was able to do it by converting a TOKEN to rule , but then what is the purpose of tokens ?
thanks

**Comment by erezsh** [comment]
Tokens provide information, like what sort of data you have (in this case, ATOM), line number, etc.

Tokens inherit from strings, so usually you can just use them as strings.

Or you can use a visitor to change them after the parse. Something like

    class TokensToStr(Visitor):
        def __default__(self, tree):
            tree.children = [str(x) if isinstance(x, Token) else x for x in tree.children]

    ...
    TokensToStr().visit( tree )

I didn't test the code, so treat it as pseudo-code. See if you can get it to work, and let me know if you get stuck.

**Comment by vsraptor** [comment]
Thanks, this seems more complex than just converting it to rule and adding transformation.

**Comment by erezsh** [comment]
I'm still not sure what was the issue, what was your workaround, and why was it necessary.
But anyway, I'm going to close the issue. Feel free to reopen it if you need to.
