### ISSUE TITLE
How do you disambiguate a nibble from a byte?

### ISSUE THREAD

**Issue by enjoysmath** [erezsh/lark#110]
self._grammar = """
        ?start: cec_message
        ?cec_message: initiator follower [":" command]
        ?command: command_id // [":" parameters]
        ?command_id: BYTE
        initiator: NIBBLE
        follower: NIBBLE
        BYTE: /[0-9A-F]{2}/
        NIBBLE: /[0-9A-F]/
        """

Changing the order of the tokens results in same UnexpectedToken error
Sometimes I want the individual nibbles and sometimes I want the byte.  This should be easy, but there's no obvious solution to me.  Thanks.

**Comment by enjoysmath** [comment]
Solveable with  an inline transformer, since ? on byte does nothing seemingly.

        self._grammar = """
        ?start: cec_message
        ?cec_message: initiator follower [":" command]
        ?command: command_id // [":" parameters]
        ?command_id: byte
        initiator: NIBBLE
        follower: NIBBLE
        byte: NIBBLE NIBBLE
        NIBBLE: /[0-9A-F]/
        """

    def byte(self, nibble1, nibble2):
        return str(nibble1) + str(nibble2)

**Comment by erezsh** [comment]
If you have a general question, and not a bug report, please ask it at the newsgroup: https://groups.google.com/forum/#!forum/lark-parser

Also, next time add the parser parameters, since behavior depends on the chosen algorithms.
