### ISSUE TITLE
generate list instead of tree ?

### ISSUE THREAD

**Issue by vsraptor** [erezsh/lark#113]
hi, If this question seems off-topic feel free to close it . That said , I have the following rule : 

		term_list : term | term_list "," term

when I parse "X, Y" , I get : 

      [['X'], 'Y']

and "X,Y,Z" : 

      [[['X'], 'Y'], 'Z']

how would I restructure the rule to get instead : 

     ['X', 'Y']
     ['X', 'Y', 'Z']

**Comment by vsraptor** [comment]
I solved it : 

		term_list : term ("," term)*

**Comment by erezsh** [comment]
How convenient ;)

But to answer your question in a more general sense: you could prefix a rule with underscore to mark it for expansion. Something like:

    term_list : term | _term_list
    _term_list: term_list "," term

Actually, that's exactly what the `*` operator expands to.
