### ISSUE TITLE
Ambiguity in GraphQL grammar

### ISSUE THREAD

**Issue by mwfrojdman** [erezsh/lark#119]
While writing a parser for [GraphQL](http://facebook.github.io/graphql/October2016/), I encountered a problem with distinguishing [Inline Fragments](http://facebook.github.io/graphql/October2016/#sec-Inline-Fragments) from [Fragment Spreads](http://facebook.github.io/graphql/October2016/#FragmentSpread). Before diving deeper, here's some examples of valid values for both. The first two ones are Fragment Spreads, the three last ones Inline Fragments:
* `... SomeName`
* `... AnotherName @myDirective`
* `... on SomeType { someField }
* `... on AnotherType @myDirective { someField }`
* `... @myDirective { someField }`

The keyword "on" causes some ambiguity that makes it difficult to define a grammar since it's both a valid name string and a keyword. The language specification excludes "on" as a name in that context, which is where the problems start.

Here's a simplified grammar that gets to the core of the issue:

```
from lark import Lark

GRAMMAR = r"""
selection: fragment_spread | inline_fragment

fragment_spread: "..." fragment_name

inline_fragment: "..." type_condition?
type_condition: "on" name

name: NAME
NAME: /[_A-Za-z][_0-9A-Za-z]*/
// same as name but excluding "on"
fragment_name: /([_A-Za-np-z][_0-9A-Za-z]*)|(o([_0-9A-Za-mo-z][_0-9A-Za-z]*|n[_0-9A-Za-z]+)?)/

%ignore /([ \t\n\r,]+)|#[^\r\n]*/
"""

PARSER = Lark(GRAMMAR, start='selection', parser='lalr', lexer='contextual')
```

Parsing the string `... on SomeName` with this grammar causes Lark take the incorrect `fragment_spread` rule instead of `inline_fragment`. The tokenizer evaluates the `o` in `on` as a token, because it matches `fragment_name`, resulting in `lark.lexer.UnexpectedInput: No token defined for: 'n' in 'n Som' at line 1 col 5`.

Whitespace is insignificant in GraphQL (hence the `%ignore`), but in this case letters should bind more closely together. Changing the order of the `fragment_spread` and `inline_fragment` rules for `selection` makes no difference. I was able to hack it working by adding an empty string RE charachter (`\b`) to the end of `fragment_name`, but that seems very fragile an approach.

Is there a better way to define the grammar with Lark in a way that avoids this ambiguity?

**Comment by erezsh** [comment]
I believe you're over-complicating the matter.

The long regex to exclude "on" is not necessary, because "on" is already a different token than NAME, and will always take precedence over it (strings always come before regexps by design).

The following grammar accepts the examples you gave but refuses `... on` -

    selection: fragment_spread | inline_fragment
    fragment_spread: "..." fragment_name
    inline_fragment: "..." type_condition
    type_condition: "on" name

    name: NAME
    NAME: /[_A-Za-z][_0-9A-Za-z]*/
    fragment_name: NAME

    %ignore /([ \t\n\r,]+)|#[^\r\n]*/   

I hope this helps. Let me know if I misunderstood you.

**Comment by mwfrojdman** [comment]
Thanks, that solved it! I feel a bit dumb now not realizing string literals take precedence, which now seems entirely logical. Not sure if it was in the docs, but if not, could be worth a mention.

And congrats on the library. Python's lacked good parsing libraries and so far this one's been the most useful by far.
