### ISSUE TITLE
Position of the parse trees

### ISSUE THREAD

**Issue by kyouko-taiga** [erezsh/lark#12]
Hey,
unless I missed something, the only way to give the location of nodes of the AST is by checking the line/column pair of the final tokens we parse. Consider for instance, let the following rule:

```
var_decl : "var" NAME ":" type_ident
```

I could get the position of the `NAME` token:

```python
class MyTransformer(Transformer):
  def var_decl(self, items):
    location = {'line': items[0].line, 'column': items[1].column}
    # ...
```

The problem with this solution is that it's difficult to get the *actual* start location of the token. In my small example, that would be the location of the "v" letter. I would have to let Lark give me the terminals (prefixing my rule with `!`), which would add noise to my parse tree.
Furthermore, it is often desirable to know the length of a node, that is not only where it starts, but also where it ends, so as to produce better compilation error messages.

Would it be possible to automatically add that information to parse trees? That way, one could get the location information as an additional parameter of the transformers:

```python
class Transformer(object):
  def transform(self, tree):
    items = [self.transform(c) if isinstance(c, Tree) else c for c in tree.children]
    try:
      f = self._get_func(tree.data)
    except AttributeError:
      return self.__default__(tree.data, tree.location, items)
    else:
      return f(items, tree.location)
  # ...

# ...

class MyTransformer(Transformer):
  def var_decl(self, items, location):
    # ...
```

Unfortunately, my suggestion would be a breaking change, because it would require transformer handlers to take an additional parameter.

Is there a better/easier way to implement what I suggest?
And if you think the whole thing isn't worth the effort, are there downsides of letting Lark add all terminals in parse trees?

**Comment by erezsh** [comment]
So, one possible solution is that Tree nodes will have two new attributes: start & end, and each one will indicate the line & column (perhaps a namedtuple?)

Will that solve your problem?

**Comment by kyouko-taiga** [comment]
Yes, that would be a perfect way to solve the problem.

**Comment by kyouko-taiga** [comment]
Note however that we would need a way to access those attributes in the transformers. As I understand, right now we only get the children of a particular node.

**Comment by erezsh** [comment]
from lark.tree import Transformer_NoRecurse 

It provides the callback functions with the tree instance, instead of its items. (I can provide a brief example)

**Comment by kyouko-taiga** [comment]
Excellent then.

**Comment by erezsh** [comment]
Okay, I just pushed the patch into master. If you initialize lark with "lexer='standard', propagate_positions=True" (both lalr and earley should work), all Tree instances will contain the attributes: line, column, end_line, end_col.
Check it out with your grammar and let me know if everything is correct. I ran some tests, but there's nothing like user input for debugging ;)

**Comment by erezsh** [comment]
Well, it's been a while without response, so I'm closing this issue.

**Comment by Erotemic** [comment]
@erezsh did this get merged?

I have a problem where I want to format a json document in a very specific way, specifically I want to add newlines and indentations to specific items shallower in the json tree, but not at deeper points. The most elegant way I can think of doing it involves using lark to make a json parser that recognizes these specific locations in the parser itself, and then I use it to generate a list of points where I will split the original json string and insert newlines / indentation (Alternatively I could just a transformer itself to emit the formatted json, but I think the splitting version may be faster?).

It doesn't look like the "standard" lexer exists anymore and I didn't see a combination that produced tree tokens with line / column / end_column attributes. Did I miss something?

**Comment by erezsh** [comment]
@Erotemic  The `meta` attribute only requires `propagate_positions=True`. It should work with any lexer. `maybe_placeholders` is True by default.

I wouldn't bet on splitting post-parse to be faster than emitting formatted JSON from the parser, but who knows, benchmarks sometimes have surprising results.
