### ISSUE TITLE
Standalone parser generator uses partial instead of functools.partial

### ISSUE THREAD

**Issue by LimEJET** [erezsh/lark#122]
The file generated by running `python -m lark.tools.standalone grammar.g > parser.py` does not prefix its calls to `functools.partial` correctly, and tries to call `partial` instead. This results in a NameError.

Tested on Python2.7.14+ and Python3.6.5rc1 with lark 0.5.5.

**Comment by erezsh** [comment]
Can you provide a pastebin of the code that gives you this error?

When I generate a parser, there are two imports:

    import functools

and

   from functools import partial

It may not be stylistically ideal, but it should prevent the error you describe.

**Comment by LimEJET** [comment]
Here's my generated [grammar_parser.py](https://gist.github.com/LimEJET/f3b9737e3a7f8270e7c868e9ad90feee). 

Also, I can't see your second import in the file:

```
$ cat grammar_parser.py | grep import
import types
import functools
from contextlib import contextmanager
    from contextlib import suppress     # Python 3
import re
```

**Comment by LimEJET** [comment]
Can confirm fixed.
