### ISSUE TITLE
Lark won't match rest of the text

### ISSUE THREAD

**Issue by popina1994** [erezsh/lark#123]
```
grammar = r""" ?start: brace_string
    brace_string: LBRACE SOME_RULE "Test" EVR 
   SOME_RULE: ... . .. . 
   EVR: /[^`]+/
"""

```
I want to match text:

"Some rule text Test sdf Some rule text sdffsd " 
I want to force parser to discard everything after "Test", but for some reason, it tries to recognize rule after token Test and it prompts me the error (unexpected token).
How to solve this issue?

**Comment by erezsh** [comment]
Please provide a valid grammar that exhibits your error, along with the code that instantiates the parser, and produces the error.

I'll be happy to help once I have everything I need to understand your problem.
