### ISSUE TITLE
Expressions with dynamic precedence ?

### ISSUE THREAD

**Issue by vsraptor** [erezsh/lark#124]
calc.py  shows how to do basic expression.
Is there a way to implement dynamic precedence ? like with  Prolog op/3.

http://www.learnprolognow.org/lpnpage.php?pagetype=html&pageid=lpn-htmlse40
http://www.swi-prolog.org/pldoc/man?predicate=op%2f3

**Comment by erezsh** [comment]
No, there isn't a simple way to dynamically update the grammar, and I don't have any plans to support it in the near future.
