### ISSUE TITLE
[wiki] error in documentation wiki

### ISSUE THREAD

**Issue by Gentle** [erezsh/lark#131]
https://github.com/erezsh/lark/wiki/Classes-Reference#visitors

I don't have write access to the wiki, but the example given in the documentation is not correct

```
class IncreaseAllNumbers(Visitor):
  def number(self, tree):
    assert self.data == "number"
    self.children[0] += 1

IncreaseAllNumbers().visit(parse_tree)
```

it must be tree.data and tree.children[0] to actually work

**Comment by erezsh** [comment]
You're right, thanks. I changed it.

Please let me know if you find other mistakes.
