### ISSUE TITLE
Rule prioritization when running earley

### ISSUE THREAD

**Issue by uriva** [erezsh/lark#16]
Hi,
So I've come to a situation where the grammar rules needs to be prioritized, some are more important than others.

What is the best way to achieve this?

I imagine something like confidence score added to the different parse trees, and an API either in the transformer or the rules themselves that determines a production rule confidence.

If we want something simpler, a simple prioritization of rules will also satisfy my needs.

Also - could it be that the order of rules affects their priority, by accident?

**Comment by erezsh** [comment]
Hi Uriva,

If you present your use-case, perhaps I can provide some insight into the best way to solve it.

Right now, ambiguity is resolved by choosing the shortest matching rule. When the length of the rules is equal, then yes, their position in the grammar marks their priority, however this is not an official feature (at least not right now), so don't rely on it.

My hunch is that adding a priority modifier should be enough for most purposes. Something in the spirit of:
    rulename.3 : some thing in side
    anotherrule.5: etc etc

Do you need something more intricate than that?

**Comment by uriva** [comment]
If it is by the position in the grammar this is good enough.

I mean - just adding it to the library contract (and ignoring the rule length).

If you feel the length of the rule is important, then introducing a priority as you suggested sounds reasonable.

Thanks!!

**Comment by uriva** [comment]
On second thought I agree. Implicitness here will be unclear.

**Comment by erezsh** [comment]
Hi Uriva,
I added this feature and pushed it to master. If you clone the repo to latest HEAD, you should be able to use it.
For an example of how to use it, see:

    tests/test_parser.py   :  test_earley_prioritization()

Its code should demonstrate proper usage and effects. Let me know if you have any questions. Let me know if it works or not.

**Comment by uriva** [comment]
I'm stumbling across the assert in common.py:45

When printing the rule that doesn't have 3 components I'm getting:

```
('import', ['_IMPORT', 'import_args', '_NL'], 'autoalias_import__IMPORT_import_args__NL', <lark.load_grammar.RuleOptions instance at 0x8d82950>)
```

Seems to be an import.

My imports:
```
%import common.NUMBER
%import common.WS
%ignore WS
```

**Comment by erezsh** [comment]
Are you sure you have the updated version? In the latest "master/HEAD", that assert is in line 44.

Add the full exception. It will help me understand why you're getting it.

**Comment by uriva** [comment]
Probably my mistake because now it seems to be working.

However I have a new error:

```
AssertionError: Priority is the same between both rules: <rule1 : token1 token2> == <rule1 : token1 token2>
```

Should this happen with the error being the same rule on both sides?

**Comment by erezsh** [comment]
No, this is a silly bug on my part. Try the latest master and see if it solves the problem for you.

**Comment by uriva** [comment]
Cool:)

**Comment by uriva** [comment]
```
lexer_conf = LexerConf(tokens, ['WS', 'COMMENT'])
TypeError: __init__() takes exactly 4 arguments (3 given)
```

**Comment by uriva** [comment]
Some of my rules have priority, but not all - I assume this is ok?

**Comment by erezsh** [comment]
That's weird. Try to erase *.pyc ?

Yeah, it has a default priority if you don't specify it.

**Comment by uriva** [comment]
Sorry I had a merge issue.
But still getting the same original error.
Could it be that the two rules are identical but still pass the equality check?

**Comment by erezsh** [comment]
Maybe. If you can give me some use case that produces this error, it would be much easier for me to correct it.

**Comment by uriva** [comment]
Ok, I'm trying to produce a minimal example.

**Comment by uriva** [comment]
The string: `d f t d f t`

And the grammar:
```
  rule3: "f" "t"

  rule4: rule3 | "f"

  rule1.1: "d"+ rule4 | "d"+ rule3

  rule2.2: rule3 "d"+

  start: (rule1 | rule2)+

  %import common.WS
  %ignore WS
```

**Comment by erezsh** [comment]
Okay. Pushed a fix to master. Try it now.

**Comment by uriva** [comment]
Seems good :+1:

**Comment by uriva** [comment]
Could you elaborate a bit on how this works?
e.g. if I several rules used in a parse, and they have different scores, how is the parse score computed? Is it simply the min/max of rules used?

**Comment by erezsh** [comment]
Basically, whenever there is an ambiguity, the resolver chooses by these conditions, in this order:

1. Priority (if and only if specified on both rules)
2. If both are part of the same rule (like rule1 in your example), choose the shortest one (if such exists)
3. Otherwise, choose the tree with the least amount of children

Just from writing it down I can see this isn't good enough (but I already knew that), but I'm not sure yet how to fix it.  If you have any ideas, let me know. I will also consider partial fixes that will solve your current problem.

**Comment by erezsh** [comment]
I'm closing this issue. Let me know if there's anything that isn't resolved.
