### ISSUE TITLE
Ambiguity bug?

### ISSUE THREAD

**Issue by uriva** [erezsh/lark#18]
When running this example:
```
grammar = """
start: ab_ b_ a_ | a_ bb_ a_
a_: "a"
b_: "b"
ab_: "ab"
bb_: "bb"
"""

l = Lark(grammar, parser='earley', ambiguity='explicit', lexer='standard')
res = l.parse('abba')
print(res.pretty())
```

The result is:
```
start
  ab_
  b_
  a_
```

Where one would expect two trees with `'_ambig'`

**Comment by erezsh** [comment]
The "standard" lexer removes some instances of ambiguity. Perhaps a better name for it would be "traditional" lexer, I will consider renaming it.

If you want to get the full parse, ambiguity and all, either use lexer="dynamic" (it's a new feature I added last week), or go for scanless (lexer=None)
