### ISSUE TITLE
Support tokens amount in range

### ISSUE THREAD

**Issue by uriva** [erezsh/lark#19]
Hi,
Would a code that adds support for the following:

```
start -> some_expression{1,3}
```

Be merged?

(The meaning here is that we are willing to parse 1-3 consecutive occurrences of `some_expression`)

**Comment by erezsh** [comment]
Sure, I'm open to this feature.
How do you plan to implement it?

**Comment by uriva** [comment]
Regexp manipulation on grammar before it is processed. (Not my code so won't take credit:))

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by erezsh** [comment]
If you mean literally running regexps on the grammar, then I won't merge such code. Using regexps, it will be limited to simple expressions only, it won't handle typos well, and it will hinder future additions to the syntax.

That way to implement this feature is to:

1) Add it to the grammar parser (in load_grammar)

2) Manipulate the resulting tree, before it's compiled into a new parser

**Comment by erezsh** [comment]
Just added support for this in latest master (not in the official release yet). Let me know if it works for you!
Syntax looks like:

    start: some_expression~1..3
