### ISSUE TITLE
Repeating a formula

### ISSUE THREAD

**Issue by brianbruggeman** [erezsh/lark#20]
I'm building a dice parser.  The lark ebnf looks something like this:

    ?expr : smath

    ?smath : smath "+" smath        -> add
           | smath "-" smath        -> sub
           | pmath

    ?pmath : pmath "*" pmath        -> mul
           | pmath "/" pmath        -> div
           | sum
           | number

    ?sum  : filter                  -> sum

    ?filter : filter "M" number     -> max
            | filter "m" number     -> min
            | filter "<" number     -> lt
            | filter "<=" number    -> le
            | filter ">" number     -> gt
            | filter ">=" number    -> ge
            | filter "!=" number    -> ne
            | filter "==" number    -> eq
            | dice

    ?dice : number "d" percentage   -> dice
          | "d" percentage          -> dice

    ?percentage : "%"               -> perc
                | number

    number : NUMBER

    %import common.NUMBER
    %import common.WS
    %ignore WS

This will parse things like: 

     4d6M3  -- roll a 6 sided die 4 times and pick the top 3
     6d6<6>1 -- roll a 6 sided die 6 times and keep all the numbers between 2 and 5

What I'd like to do is:

    6x4d6M3 -- roll the 6 sided die 4 times and pick the top 3 ... repeat 6 times

or

    4d6M3x6 -- roll the 6 sided die 4 times and pick the top 3 ... repeat 6 times

Is there a mechanism to control something like that?  More or less, it seems like I'd need to hold off on actually reducing the formula immediately so I can determine how many times to run the formula and then calculate the formula.

**Comment by erezsh** [comment]
Hi Brian,

It seems to me that you have two options:

1) Run two separate transformers. The first one will duplicate instructions inside the tree, and the second one will evaluate the instructions. It's simple, but inefficient.

2) Write an interpreter (top->bottom) instead of a transformer (which is bottom->top). There is a relevant example in this blog post I wrote: http://blog.erezsh.com/how-to-write-a-dsl-in-python-with-lark

**Comment by brianbruggeman** [comment]
Thank you!  This worked really well.
