### ISSUE TITLE
Naming rule parts

### ISSUE THREAD

**Issue by akrasuski1** [erezsh/lark#23]
I wonder if you thought of adding support to naming parts of the rules, such as:
```
ifstmt: "if" "(" expr: condition ")" "{" (stmt*): body "}"
```
(syntax could be changed of course)

This would be helpful because, as far as I know, the only way to refer to children of the tree is by `tree.children[0]` etc. - this feature would allow something akin to `tree.condition` or `tree["condition"]`.

**Comment by akrasuski1** [comment]
On the other hand, this could be emulated by adding new non-terminals to the grammar (`condition: expr` in this case) and then use `.find_data("condition")` method. This is undocumented though, I only found it after looking at available methods.

**Comment by erezsh** [comment]
You're right, I should document the Tree class properly. I'll keep this issue open as a reminder.

Also, yes, if you want to name parts of a rule, it's better to turn these parts into separate rules. It's syntactically simpler, and easier to read.

**Comment by erezsh** [comment]
Added documentation here: https://github.com/erezsh/lark/wiki/Classes
