### ISSUE TITLE
Earley fails when parsing comments

### ISSUE THREAD

**Issue by psboyce** [erezsh/lark#24]
I'm attempting to parse a grammar that uses '!' or '//' for commenting everything starting with the token to the end of the line. Everything is fine in LALR(1) but Earley throws a ParseError.

The code in question, with the grammar;

    from __future__ import print_function
    from lark import Lark
    
    grammar = r"""
    COMMENT: /(!|(\/\/))[^\n]*/
    %ignore COMMENT
    
    %import common.WS
    // _WS: WS
    
    %import common.INT
    int_stmnt: "INT"i WS+ INT WS*
    """
    
    parser = Lark(grammar, start="int_stmnt", parser="earley")
    
    tree = parser.parse("int 1 ! This is a comment\n")
    
    print(tree.pretty())

For emphasis, the regular expression I'm using for comments; `COMMENT: /(!|(\/\/))[^\n]*/`

The traceback from this script when run as is;

    Traceback (most recent call last):
      File "lark_earley_bug.py", line 18, in <module>
        tree = parser.parse("int 1 ! This is a comment\n")
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lark/lark.py", line 193, in parse
        return self.parser.parse(text)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lark/parser_frontends.py", line 144, in parse
        return self.parser.parse(text)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lark/parsers/xearley.py", line 128, in parse
        raise ParseError('Incomplete parse: Could not find a solution to input')
    lark.common.ParseError: Incomplete parse: Could not find a solution to input

The error free output of this script when using the LALR parser;

    int_stmnt
       
      1
       
You'll find that removing the comment will also get the error free output from Earley.

**Comment by erezsh** [comment]
Hi, this is a bug with the dynamic lexer. Thanks for providing an example, I'll try to fix it soon.
Meanwhile, your code should work with:
    parser = Lark(grammar, start="int_stmnt", parser="earley", lexer='standard')

**Comment by erezsh** [comment]
Fixed in latest master.
