### ISSUE TITLE
Parser failes with Context: <no context>

### ISSUE THREAD

**Issue by DuyguA** [erezsh/lark#27]
Hello,

I want to parse out the  "interesting" parts of a sentence and discard the rest.  For instance, I want to parse out only strings of the form word  "parsley" followed by an integer, e.g. "parsley 1", "parsley 212"...What is the correct way to do it?

Here's my tiny grammar:

```
rules = u"""
       sentence: (parsley|rubbish)+
       parsley: PARSLEY INT
       rubbish: RUBBISH
       
       PARSLEY: "parsley"
       RUBBISH: /[^\s]+/

       %import common.INT
       %import common.WS
       %ignore WS
       """
```

If I parse with Earley, parser doesn't parse anything at all.

```
>>> parser = Lark(rules, start="sentence")
>>> parser.parse(u"I saw parsley 12")
Tree(sentence, [Tree(rubbish, [u'k']), Tree(rubbish, [u'dk']), Tree(rubbish, [Token(RUBBISH, u'kd')]), Tree(rubbish, [Token(RUBBISH, u'djdj')]), Tree(rubbish, [Token(RUBBISH, u'parsley')]), Tree(rubbish, [Token(RUBBISH, u'12')])])
```

 If I parse with LALR, it works if
 
```
>>> parser.parse(u"I saw a parsley 1")
Tree(sentence, [Tree(rubbish, [Token(RUBBISH, u'I')]), Tree(rubbish, [Token(RUBBISH, u'saw')]), Tree(rubbish, [Token(RUBBISH, u'a')]), Tree(parsley, [Token(PARSLEY, u'parsley'), Token(INT, u'1')])])
```
But if there are "parsley" rule parts it fails:

```
>>> parser.parse(u"I saw a parsley 1, maybe another parsley without a number")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/lark/lark.py", line 193, in parse
    return self.parser.parse(text)
  File "/usr/local/lib/python2.7/dist-packages/lark/parser_frontends.py", line 31, in parse
    return self.parser.parse(tokens)
  File "/usr/local/lib/python2.7/dist-packages/lark/parsers/lalr_parser.py", line 61, in parse
    action, arg = get_action(token.type)
  File "/usr/local/lib/python2.7/dist-packages/lark/parsers/lalr_parser.py", line 36, in get_action
    raise UnexpectedToken(token, expected, seq, i)
lark.common.UnexpectedToken: Unexpected token Token(RUBBISH, u'without') at line 1, column 41.
Expected: [u'INT']
Context: <no context>
>>> parser.parse(u"I saw a parsley 1, maybe another 12 without")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/lark/lark.py", line 193, in parse
    return self.parser.parse(text)
  File "/usr/local/lib/python2.7/dist-packages/lark/parser_frontends.py", line 31, in parse
    return self.parser.parse(tokens)
  File "/usr/local/lib/python2.7/dist-packages/lark/parsers/lalr_parser.py", line 61, in parse
    action, arg = get_action(token.type)
  File "/usr/local/lib/python2.7/dist-packages/lark/parsers/lalr_parser.py", line 36, in get_action
    raise UnexpectedToken(token, expected, seq, i)
lark.common.UnexpectedToken: Unexpected token Token(INT, u'12') at line 1, column 33.
Expected: [u'PARSLEY', u'RUBBISH', '$end']
Context: <no context>
```

What is the correct way to parse out strings of interest from a bigger string? Thanx in advance!

**Comment by erezsh** [comment]
Hi, you should really just use a regular expression for that.
Something like

    import re
    re.findall('parsley\s+\d+', some_string)

Lark is meant for recognizing well-defined structure in text.

**Comment by DuyguA** [comment]
Hello,

I gave tiny lang as an example, I'm an indeed parsing time expressions (context free and more complicated of course:) )  I can't disclose the grammar here. Something like this:

> Can we meet **next year, late March / early April**?

or

> We can meet **tomorrow 12.00-14.00 or Wednesday 15.00-16.00**.

So, I want to both extract the strings, also parse the expression at the same time. Can we extract parsed strings from the outer string, that was my question.

**Comment by erezsh** [comment]
Yes, it's possible, but not recommended in terms of performance.

I recommend that you use a two stage approach:

1) Use a regular expression to capture every phrase that might be relevant (As a whole string)

2) Parse each matched string (with Earley, not LALR), and throw away those that fail to parse. 

Another suggestion is to use PyParsing for this. While Lark is generally better, PyParsing has the "scan()" function which seems to do what you want (maybe?).

**Comment by DuyguA** [comment]
Thanks for the prompt answer!

- I'm unhappy with performance of PyParsing in general. Input strings to this parser might be "long", so I'm not sure really, I'll give it a try anyway.

- Why am I not surprised that I'll fall back onto good, old regex at the end of the day? :1st_place_medal: 

Thanks for suggestions, issue can be closed.
