### ISSUE TITLE
Comments in grammar?

### ISSUE THREAD

**Issue by zDawG** [erezsh/lark#29]
Hi there, a useful feature is to have comments in grammars.
I couldn't find any support for this perusing the code.
Am I missing something or is the feature not there?
Any plans to add?

Thanks!
Nice framework.

**Comment by erezsh** [comment]
Hi, there is support for comments in grammars.
You can see them in use here: https://github.com/erezsh/lark/blob/master/examples/python3.g

Thanks, I'm glad you like it! May I ask what you're using it for?

**Comment by FruitfulApproach** [comment]
> Hi, there is support for comments in grammars. You can see them in use here: https://github.com/erezsh/lark/blob/master/examples/python3.g
> 
> Thanks, I'm glad you like it! May I ask what you're using it for?

Yeah.... that link is broken

**Comment by jmishra01** [comment]
@zDawG  - You can use '//' to write comments in the grammar. 

For more info, please check this [link](https://lark-parser.readthedocs.io/en/latest/grammar.html).
