### ISSUE TITLE
Grammar sends Earley implementation to an infinite loop

### ISSUE THREAD

**Issue by erezsh** [erezsh/lark#3]
Earley implementation never terminates when running with the input "a", and the following grammar:
> start: a
> a:  a | "a"

Of course the grammar is badly formed, but since we aspire to parse "any grammar", an error is a more appropriate behavior.

**Comment by lucaswiman** [comment]
@erezsh If I understand correctly, this grammar is not malformed, but also enters into an infinite loop:
```python
from lark import Lark

l = Lark('''
  start: bar+
  bar: /a|b|c*/ "foo"
''')

l.parse('afoobfooccfoo')
```

**Comment by lucaswiman** [comment]
It seems the issue is that the regex can match zero characters. This one works fine:
```
Lark('''
  start: bar+
  bar: /a|b|c+/ "foo"
''')
```
and this one fails in the same way as the example above:
```
Lark('''
  start: bar+
  bar: /a|b|/ "foo"
''')
```

**Comment by erezsh** [comment]
Thanks, good catch!

I think the correct response is to forbid empty regexps.

**Comment by erezsh** [comment]
Both issues resolved.

**Comment by erezsh** [comment]
Fixed!
