### ISSUE TITLE
Issues with parser translated from Nearley

### ISSUE THREAD

**Issue by kasbah** [erezsh/lark#30]
Hey I managed to re-work and [translate my nearley grammar](https://github.com/monostable/electro-grammar/tree/python/python). It works but I noticed some issues (you can compare to the JS demo [here](https://monostable.github.io/electro-grammar/)).

First, I get a `Token` when I am expecting a string:

```python
import electro_grammar
electro_grammar.parse('100uF 0805')
Out[11]: [{'type': 'capacitor'}, {'capacitance': 0.0001}, None, {'size': Token(__ANONSTR_103, '0805')}, None]
```

Second, it goes for an infinite loop when I add certain descriptions:

```python
electro_grammar.parse('100uF 0805 5%')
...
electro_grammar.parse('100uF 0805 x7r')
...
```

When I Ctrl-C I noticed in both stack traces:

```
earley.py in add(self, items)
    109             if item.is_complete:
    110                 # XXX Potential bug: What happens if there's ambiguity in an empty rule?
--> 111                 if item.rule.expansion and item in self.completed:
    112                     old_tree = self.completed[item].tree
    113                     if old_tree.data != '_ambig':
```

<details>
<summary>Full stack trace</summary>

```
In [15]: electro_grammar.parse('100uF 0805 x7r')
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-15-8b9cfb50244a> in <module>()
----> 1 electro_grammar.parse('100uF 0805 x7r')

~/projects/electro-grammar/electro-grammar/python/electro_grammar.py in parse(text)
    683 parser = Lark(grammar, start="n_main")
    684 def parse(text):
--> 685     return TranformNearley().transform(parser.parse(text))
    686 

~/projects/electro-grammar/electro-grammar/python/venv/src/lark-parser/lark/lark.py in parse(self, text)
    191 
    192     def parse(self, text):
--> 193         return self.parser.parse(text)
    194 
    195         # if self.profiler:

~/projects/electro-grammar/electro-grammar/python/venv/src/lark-parser/lark/parser_frontends.py in parse(self, text)
    142 
    143     def parse(self, text):
--> 144         return self.parser.parse(text)
    145 
    146 def get_frontend(parser, lexer):

~/projects/electro-grammar/electro-grammar/python/venv/src/lark-parser/lark/parsers/xearley.py in parse(self, stream, start_symbol)
    119 
    120 
--> 121         predict_and_complete(column)
    122 
    123         # Parse ended. Now build a parse tree

~/projects/electro-grammar/electro-grammar/python/venv/src/lark-parser/lark/parsers/xearley.py in predict_and_complete(column)
     75                         if new_item.similar(item):
     76                             raise ParseError('Infinite recursion detected! (rule %s)' % new_item.rule)
---> 77                     column.add(new_items)
     78 
     79         def scan(i, token, column):

~/projects/electro-grammar/electro-grammar/python/venv/src/lark-parser/lark/parsers/earley.py in add(self, items)
    109             if item.is_complete:
    110                 # XXX Potential bug: What happens if there's ambiguity in an empty rule?
--> 111                 if item.rule.expansion and item in self.completed:
    112                     old_tree = self.completed[item].tree
    113                     if old_tree.data != '_ambig':

~/projects/electro-grammar/electro-grammar/python/venv/src/lark-parser/lark/parsers/earley.py in __eq__(self, other)
     58 
     59     def __eq__(self, other):
---> 60         return self.similar(other) and (self.tree is other.tree or self.tree == other.tree)
     61 
     62     def __hash__(self):

~/projects/electro-grammar/electro-grammar/python/venv/src/lark-parser/lark/tree.py in __eq__(self, other)
     42     def __eq__(self, other):
     43         try:
---> 44             return self.data == other.data and self.children == other.children
     45         except AttributeError:
     46             return False

~/projects/electro-grammar/electro-grammar/python/venv/src/lark-parser/lark/tree.py in __eq__(self, other)
     42     def __eq__(self, other):
     43         try:
---> 44             return self.data == other.data and self.children == other.children
     45         except AttributeError:
     46             return False

~/projects/electro-grammar/electro-grammar/python/venv/src/lark-parser/lark/tree.py in __eq__(self, other)
     40             self.children[i:i+1] = kid.children
     41 
---> 42     def __eq__(self, other):
     43         try:
     44             return self.data == other.data and self.children == other.children

KeyboardInterrupt: 

```

</details>

<br />

I realize it is likely due to ambiguity in my grammar and I am working to reduce it (but not sure it _can_ be totally unambiguous).  Any hints on how best to resolve would be very much appreciated. 

TODO:
- [ ] See why `Tokens` appear from parsing string literals
- [ ] Investigate if instantiating with `parser='earley', lexer=None, earley__all_derivations=False` is closer to Nearley's implementation
- [ ] Investigate why this [edit](https://github.com/monostable/electro-grammar/commit/1c4e4dd1d73b3ed66929f4442633b391dbf4cdc2#diff-3283b6cc704d3d52b7fb42a0c8c683a2L1) is needed for consistent results between Nearley and Lark.

**Comment by erezsh** [comment]
Hi, it is probably not due to ambiguity, but due to an infinite recursion inside your grammar. Ideally Lark should detect it and provide a useful error message, so it's a bug that it doesn't.
Meanwhile, you can solve this by instantiating Lark with the following arguments:

    parser = Lark(grammar, start="n_main", parser='earley', lexer=None, earley__all_derivations=False)

This mode of operation might be closer to Nearley's implementation anyway (however, I'm not sure, it needs verifying), so perhaps it is better to use it for all translated Nearley programs?

**Comment by kasbah** [comment]
Cool, that works! Any idea what's going on with the `Token` things? With the new settings the it seems even worse: 
```python
electro_grammar.parse('100uf 0805')
Out[10]: [{'type': 'capacitor'}, {'capacitance': 0.0001}, None, {'size': Token(CHAR, '0')}, None]
electro_grammar.parse('100uf 1206')
Out[11]: [{'type': 'capacitor'}, {'capacitance': 0.0001}, None, {'size': Token(CHAR, '1')}, None]
```

The relevant definitions are in [package_size.ne](https://github.com/monostable/electro-grammar/blob/61e76ad57e6246454c68020f502b3acbb723e6ee/src/package_size.ne) which makes use of some utility functions from [util.ne](https://github.com/monostable/electro-grammar/blob/61e76ad57e6246454c68020f502b3acbb723e6ee/src/util.ne).

**Comment by kasbah** [comment]
Ok, [this edit](https://github.com/monostable/electro-grammar/commit/1c4e4dd1d73b3ed66929f4442633b391dbf4cdc2#diff-3283b6cc704d3d52b7fb42a0c8c683a2L1) seems to make it work for both Nearley and Lark but I am not really sure why this is treated differently in Lark. Any insight?

**Comment by erezsh** [comment]
My best guess is that joining the elements to a string, fixes the equality test, and allows lark to merge the two derivations into one.

It looks like it might be a bug, but it's too subtle to say for sure. If you can narrow it down to a smaller grammar I might be able to track what's going on.

**Comment by erezsh** [comment]
If you still need help re the Token instances, let me know.

**Comment by kasbah** [comment]
I have a work around for my own grammar and haven't encountered any further issues but it seems like it would be a good idea to add a test and fix it.

**Comment by erezsh** [comment]
Definitely a good idea. We can keep it open.

**Comment by erezsh** [comment]
Hi, any chance you can check if this bug still exists with latest master? If it's not, I can close the issue.

**Comment by kasbah** [comment]
I will certainly have another look when I get time, though I am not sure what "the bug" is any more. I kept this issue open for the two tasks I edited in at the top: 

>- See why `Tokens` appear from parsing string literals
>- Investigate if instantiating with `parser='earley', lexer=None, earley__all_derivations=False` is closer to Nearley's implementation

**Comment by erezsh** [comment]
Oh ok..

Tokens are an intended feature, but they behave just like strings. I'm not sure what is the problem.

Lark doesn't try to be Nearley's clone. But if there is a mode that emulates Nearley better let me know and I'll use it for the conversion tool.

**Comment by kasbah** [comment]
I see, I guess the confusion arose because their appearance seemed to be inconsistent. I shall investigate soon and will probably have more questions then.

**Comment by kasbah** [comment]
I added another todo for the bug you were probably thinking of (and I almost forgot about):

>Investigate why [this edit](https://github.com/monostable/electro-grammar/commit/1c4e4dd1d73b3ed66929f4442633b391dbf4cdc2#diff-3283b6cc704d3d52b7fb42a0c8c683a2L1) is needed for consistent results between Nearley and Lark. 

But maybe this is just me being confused about Tokens?

**Comment by erezsh** [comment]
Hi, I'm assuming this issue is resolved, or no longer relevant. Feel free to reopen it if you need to.
