### ISSUE TITLE
Parsing quasi-xml file with punctuation and special chars

### ISSUE THREAD

**Issue by usptact** [erezsh/lark#34]
I have the data that looks like this:
`<LABEL="some value"> <OTHER="something else">`

Each line contains 0 or more such XML tags. The tag labels are all caps but the value is basically any string, including punctuation.

I came up with the following grammar but couldn't get it working on string where values contain characters, digits, punctuation and other chars.

    ltr_parser = Lark(r"""
    ?line: facet* 
    ?facet: "<" label "=\"" value+ "\">"
    label: /[A-Z]+/
    value: /.+?/
    
    %import common.NUMBER
    %import common.WORD
    %import common.ESCAPED_STRING   -> STRING
    %ignore " "
    """, start='line')

    text = '<TAG="value value"> <BUZ="jazz 100%">'

    tree = ltr_parser.parse(text)
    print(tree)

Is there a way to reliably match the "value" that can contain different characters, including punctuation and special symbols?

Thanks

**Comment by erezsh** [comment]
In general, and especially in Lark, simpler is better.

ltr_parser = Lark(r"""
?line: facet* 
?facet: "<" label "=" STRING ">"
label: /[A-Z]+/

%import common.NUMBER
%import common.WORD
%import common.ESCAPED_STRING   -> STRING
%ignore " "
""", start='line')

**Comment by usptact** [comment]
Thank you, @erezsh this change did the trick! I was too focused on "value" and didn't see that there already exists a terminal node which will match!
