### ISSUE TITLE
ParseError on extremely simple grammar

### ISSUE THREAD

**Issue by LogicalDash** [erezsh/lark#35]
I'm building a grammar to process a kind of assignment statement. I started from the beginning and built one that just finds the left and right sides, but this never completes parsing.

```
degen_expex = Lark("""
start: lhs "=" rhs

lhs: ESCAPED_STRING

rhs: ESCAPED_STRING

%import common.ESCAPED_STRING
%import common.WS
%ignore WS
""")

deparsed = degen_expex.parse('foo=bar')
```

My actual grammar is more complex than this, of course. It doesn't complete parsing either, but I feel like it would be pointless to debug that if I can't get the most basic thing working.

I'm in Python 3.6 on Windows with Lark version 0.3.7

**Comment by LogicalDash** [comment]
It's because I made bad assumptions about what an ESCAPED_STRING was

**Comment by erezsh** [comment]
No problem, parsing can be confusing. We're using a language within a language to parse a language, and sometimes it's hard to keep track of what belongs where.
