### ISSUE TITLE
Is there a Java grammar for Lark

### ISSUE THREAD

**Issue by sriniiyer** [erezsh/lark#36]
Would like to parse Java. Right now, Im translating a ANTLR Java grammar to the Lark format, but do you know if there is one available already? Thanks!

**Comment by erezsh** [comment]
Hi, none currently exists, but the translation should be very straightforward.

Let me know if you need any help.

**Comment by sriniiyer** [comment]
Thanks! I ended up sticking with antlr for which the grammar already exists.

**Comment by erezsh** [comment]
Okay, good luck!
