### ISSUE TITLE
correct (as far as I can tell) but large grammar triggers exception in version 0.4.1

### ISSUE THREAD

**Issue by till314** [erezsh/lark#37]
At the end of the file parse_tree_builder.py in the class ParseTreeBuilder at line 150-151 you use:

if hasattr(callback, callback_name):
    raise GrammarError("Rule expansion '%s' already exists in rule %s" % (' '.join(expansion), origin))

The grammar I use triggers this exception. Since I couldn't find any concrete reason why the callback name needs to be constructed according to this rule I changed these two lines to

from random import randint
while hasattr(callback, callback_name):
    callback_name = 'autoalias_%s_%s_%d' % ( _origin, '_'.join(expansion), randint(0, 999))
                  
as a temporary solution which avoided the exception and got my test cases to run. 
Are there any problems with this change (besides a certain ugliness)?

**Comment by erezsh** [comment]
Well, why do you need two similar expansions for the same rule?

It doesn't seem like good practice. It seems like fertile ground for subtle bugs down the line, even though I can't think of a specific one right now.

**Comment by till314** [comment]
Thanks. I found the culprit. The program used to transform the Fortran grammar I used to the Lark format
did not check whether identical rules were generated.  

But since you don't always have complete control over the grammars something slightly more flexible (like quietly ignoring identical rules, or just printing a warning) would be nice.
