### ISSUE TITLE
regex rule failing with whitespace

### ISSUE THREAD

**Issue by LivingInSyn** [erezsh/lark#39]
I have a regex rule in my grammar that looks like this (modified from the python sample):

`comment: /\/\/[^\n]*/`

Which matches fine when a comment does NOT have a trailing space, like this:

`//I am a comment`

However, when there IS a trailing space, like this:

`//I am a comment `

It fails, resulting in a ''Incomplete parse: Could not find a solution to input'' error. 

The regex works fine in python, like so:
```
>>> teststring = "//I am a comment "
>>> c = re.compile('\/\/[^\n]*')
>>> c.match(teststring)
<_sre.SRE_Match object; span=(0, 17), match='//I am a comment '>
```

which does match the trailing whitespace

**Comment by LivingInSyn** [comment]
This does not appear to be the case when using parser='lalr'

**Comment by erezsh** [comment]
If you can use 'lalr', then do so. It's also significantly faster.

Can you check if it happens with parser='earley', lexer=None ?

**Comment by LivingInSyn** [comment]
parser="earley", lexer=None:
    Fails
parser="earley":
    Fails
lexer=None:
    'Scanless parsing (lexer=None) requires all tokens to have a width of 1 (terminal ANONRE_15: [0-9]+ is (1, 2147483647))'

**Comment by erezsh** [comment]
Ok. If at any point you want to provide an example that's failing, I'll be happy to fix it.

**Comment by LivingInSyn** [comment]
Here is a minimal example in 2 files:

file grammar.g:

```
start: comment+

comment: /\/\/[^\n]*/

%import common.ESCAPED_STRING
%import common.WS
%ignore WS
```

sample.py
```
from lark import Lark

comments = '''//no whitespace
//whitespace '''

with open('grammar.g','r') as grammarfile:
    parser = Lark(grammarfile.read(), parser='lalr')
    print(parser.parse(comments).pretty())
    
    grammarfile.seek(0)
    
    parser_def = Lark(grammarfile.read())
    print(parser_def.parse(comments).pretty())
```

**Comment by erezsh** [comment]
Hi, sorry but your example code runs perfectly. Can you make sure you're using commit ec7da3b ?

**Comment by erezsh** [comment]
(It's the latest commit to master)
