### ISSUE TITLE
Ambiguity resolution not working as expected

### ISSUE THREAD

**Issue by wiseman** [erezsh/lark#46]
I'm getting some results that I didn't expect, so maybe my expectations are wrong.

```
template_parser = lark.Lark("""
  expr : (varref | literal)+
  varref.5 : "${" VARNAME "}"
  literal.1 : LITERAL
  LITERAL : /.+/
  VARNAME : /[a-z]+/
""", start='expr', debug=True, parser='earley')

print(template_parser.parse('${foo}').pretty())
```

The result is

```
expr
  literal	$
  literal	{f
  literal	foo
  literal	oo}
```

This result surprises me in three ways:

1. I expected to get this, since the `varref` rule has higher priority than `literal`:

```
  expr
    varref	foo
```

2. If it's going to go with a literal result, why doesn't it choose this simpler tree?

```
  expr
    literal	${foo}
```

3. How are parts of the input showing up in multiple terminals? For example, `f` shows up twice, in `{f` and `foo`.

**Comment by erezsh** [comment]
Hi, sorry it took me a while to get to this issue. I just pushed a fix to `master`, which should resolve all these incorrect behaviors.
Please test it and let me know if it's solved.

**Comment by erezsh** [comment]
I'm assuming this issue is resolved. Feel free to reopen it otherwise.
