### ISSUE TITLE
Advice on implementing precedence with parentheses?

### ISSUE THREAD

**Issue by flewellyn** [erezsh/lark#52]
I'm working on a grammar for a logical expression mini-language, and I have hit a snag: I can't figure out how to implement explicit precedence using parentheses in the grammar.  I know about rule priorities (and I'm making use of them), but I want to be able to use parentheses to override precedence.

How would I go about doing something like this in the grammar?  Or is it something I would need to implement in the tree transformer?

**Comment by erezsh** [comment]
Parentheses are almost a built-in feature in standard parsers.
Review the calculator example for a simple demonstration of it: https://github.com/erezsh/lark/blob/master/examples/calc.py
Let me know if you still have questions.

**Comment by flewellyn** [comment]
I had a look at this, and I'm not sure if I got the idea correctly.

Here's the grammar I'm trying to parse:

`expression: comparison

andclause: (expression "AND"i expression)
           | (orclause "AND"i expression)
           | (expression "AND"i orclause)

orclause: (expression "OR"i expression)
          | (notclause "OR"i expression)
          | (expression "OR"i notclause)

notclause: "NOT"i (expression | comparison)

comparison: value cmp value
            | "(" expression ")"

cmp: EQ|NE|LT|GT|LE|GE

value: STRING -> stringval
       | NUMBER -> numeric
       | CNAME -> ident
       | "true"i -> true
       | "false"i -> false
       | "null"i -> null

%import common.CNAME
DOUBLE_QUOTED_STRING  : /"[^"]*"/
SINGLE_QUOTED_STRING  : /'[^']*'/
STRING: SINGLE_QUOTED_STRING | DOUBLE_QUOTED_STRING
EQ: "="
NE: "!="
LT: "<"
GT: ">"
LE: "<="
GE: ">="
%import common.SIGNED_NUMBER -> NUMBER
%import common.WS
%ignore WS`

I have a feeling that there's something obvious that I'm missing.

**Comment by flewellyn** [comment]
I was right: there was something I was missing. I'd overcomplicated the rules, and what I really needed was something more sensibly recursive.  This is what ended up working:

```
?expression: (comparison | andclause | orclause | notclause)

andclause: (expression "AND"i expression)

orclause: (expression "OR"i expression)

notclause: "NOT"i (expression)

?comparison: value cmp value
            | "(" expression ")"
```

(I omitted the rest of the rules and terminal definitions.)

So, I think I have it figured out.  Thanks for your advice!

**Comment by erezsh** [comment]
Yes, this looks much better. It's not ideal for precedence parsing, but it should work if you add priorities.
Ideally, you would enforce the precedence in the rules, for example:

    orclause: andclause ("AND"i andclause)*

But whatever works
