### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by MareoRaft** [erezsh/lark#53]
Hello!

I have (unfortunately) a complicated syntax to parse.  I will (no longer) include the entire file at the end.  The original syntax had the line

    type_expression:"(" radix_type ")"|adjective_cluster type_expression|radix_type

which results in a "recursion error":

        def predict_and_complete(column):
            while True:
                to_predict = {x.expect for x in column.to_predict.get_news()
                              if x.ptr}  # if not part of an already predicted batch
                to_reduce = column.to_reduce.get_news()
                if not (to_predict or to_reduce):
                    break
    
                for nonterm in to_predict:
                    column.add( predict(nonterm, column) )
                for item in to_reduce:
                    new_items = list(complete(item))
                    for new_item in new_items:
                        if new_item.similar(item):
    >                       raise ParseError('Infinite recursion detected! (rule %s)' % new_item.rule)
    E                       lark.common.ParseError: Infinite recursion detected! (rule <type_expression : adjective_cluster type_expression>)
    
    /usr/local/lib/python3.6/site-packages/lark/parsers/xearley.py:76: ParseError

In an attempt to solve this error, I changed the line to

    type_expression:(adjective_cluster)* ("(" radix_type ")"|radix_type)

It successfully suppresses the "recursion error", but now the script runs indefinitely, which may be related to something else entirely.  My test code says

	with open('test_easy.miz') as file:
		string = file.read()
	ar = ArticleReader()
	parseTree = ar.parse(string)
	print(parseTree)

and the file I'm trying to parse is

    environ
    
    begin
    
    registration
      cluster reflexive -> complete for 1-element RelStr;
      coherence;
    end;
    
    definition
      let T be RelStr;
      mode type of T is Element of T;
    end;
    ...
    

and the parser is 

    import re
    
    from lark import Lark
    
    
    class ArticleReader:
    
    
    	def __init__(self):
    		self._init_parser()
    
    	def parse(self, string):
    		""" Takes in a string (.miz file content) and parses it """
    		# Remove any comments
    		commentless_string = re.sub(r'\s*::.*', '', string, re.MULTILINE)
    
    		# Parse
    		parseTree = self._parser.parse(commentless_string)
    		return parseTree.pretty()
    
    	def _init_parser(self):
    		self._parser = Lark(r"""
    			upperalphas: "A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"|"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"
    			loweralphas: "a"|"b"|"c"|"d"|"e"|"f"|"g"|"h"|"i"|"j"|"k"|"l"|"m"|"n"|"o"|"p"|"q"|"r"|"s"|"t"|"u"|"v"|"w"|"x"|"y"|"z"
    			alphas: upperalphas | loweralphas
    			nums: "0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"
    			upperalphanums: upperalphas | nums
    			alphanums: alphas | nums
    			non_zero_digit: "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
    			numeral: non_zero_digit ("0" | non_zero_digit)*
    			identifier: (alphanums)+
    			file_name: upperalphas /("A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"|"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"|"0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9" | "_"){4,7}/
    			symbol: /(?:(?!::)[^\s])+/
    
    			private_definition_parameter:"$1"|"$2"|"$3"|"$4"|"$5"|"$6"|"$7"|"$8"|"$9"|"$10"
    			postqualified_variable:identifier
    			postqualifying_segment:postqualified_variable ("," postqualified_variable)* [("is"|"are") type_expression]
    			postqualification:"where" postqualifying_segment ("," postqualifying_segment)*
    			term_expression_list:term_expression ("," term_expression)*
    			adjective_arguments:term_expression_list|"(" term_expression_list ")"
    			arguments:term_expression|"(" term_expression_list ")"
    			term_expression:"(" term_expression ")"|[arguments] functor_symbol [arguments]|left_functor_bracket term_expression_list right_functor_bracket|functor_identifier "(" [term_expression_list] ")"|structure_symbol "(#" term_expression_list "#)"|"the" structure_symbol "of" term_expression|variable_identifier|"{" term_expression (postqualification)* ":" sentence "}"|"the" "set" "of" "all" term_expression (postqualification)*|numeral|term_expression "qua" type_expression|"the" selector_symbol "of" term_expression|"the" selector_symbol|"the" type_expression|private_definition_parameter|"it"
    			type_expression_list:type_expression ("," type_expression)*
    			radix_type:mode_symbol ["of" term_expression_list]|structure_symbol ["over" term_expression_list]
    			structure_type_expression:"(" structure_symbol ["over" term_expression_list] ")"|adjective_cluster structure_symbol ["over" term_expression_list]
    			type_expression:(adjective_cluster)* ("(" radix_type ")"|radix_type)
    			qualification:("being"|"be") type_expression
    			variables:variable_identifier ("," variable_identifier)*
    			qualified_segment:variables qualification
    			explicitly_qualified_variables:qualified_segment ("," qualified_segment)*
    			implicitly_qualified_variables:variables
    			qualified_variables:implicitly_qualified_variables|explicitly_qualified_variables|explicitly_qualified_variables "," implicitly_qualified_variables
    			quantified_formula_expression:"for" qualified_variables ["st" formula_expression] ("holds" formula_expression|quantified_formula_expression)|"ex" qualified_variables "st" formula_expression
    			atomic_formula_expression:[term_expression_list] [("does"|"do") "not"] predicate_symbol [term_expression_list] ([("does"|"do") "not"] predicate_symbol term_expression_list)*|predicate_identifier "[" [term_expression_list] "]"|term_expression "is" adjective (adjective)*|term_expression "is" type_expression
    			formula_expression:"(" formula_expression ")"|atomic_formula_expression|quantified_formula_expression|formula_expression "&" formula_expression|formula_expression "&" "..." "&" formula_expression|formula_expression "or" formula_expression|formula_expression "or" "..." "or" formula_expression|formula_expression "implies" formula_expression|formula_expression "iff" formula_expression|"not" formula_expression|"contradiction"|"thesis"
    			sentence:formula_expression
    			proposition:[label_identifier ":"] sentence
    			conditions:"that" proposition ("and" proposition)*
    			scheme_number:numeral
    			definition_number:numeral
    			theorem_number:numeral
    			library_scheme_reference:article_name ":" "sch" scheme_number
    			library_reference:article_name ":" (theorem_number|"def" definition_number) ("," (theorem_number|"def" definition_number))*
    			local_scheme_reference:scheme_identifier
    			local_reference:label_identifier
    			scheme_reference:local_scheme_reference|library_scheme_reference
    			reference:local_reference|library_reference
    			references:reference ("," reference)*
    			scheme_justification:"from" scheme_reference ["(" references ")"]
    			straightforward_justification:["by" references]
    			proof:"proof" reasoning "end"
    			simple_justification:straightforward_justification|scheme_justification
    			justification:simple_justification|proof
    			diffuse_statement:[label_identifier ":"] "now" reasoning "end" ";"
    			iterative_equality:[label_identifier ":"] term_expression "=" term_expression simple_justification ".=" term_expression simple_justification (".=" term_expression simple_justification)* ";"
    			type_change_list:(equating|variable_identifier) ("," (equating|variable_identifier))*
    			type_changing_statement:"reconsider" type_change_list "as" type_expression simple_justification ";"
    			choice_statement:"consider" qualified_variables "such" conditions simple_justification ";"
    			compact_statement:proposition justification ";"
    			linkable_statement:compact_statement|choice_statement|type_changing_statement|iterative_equality
    			statement:["then"] linkable_statement|diffuse_statement
    			example:term_expression|variable_identifier "=" term_expression
    			exemplification:"take" example ("," example)* ";"
    			diffuse_conclusion:"thus" diffuse_statement|"hereby" reasoning "end" ";"
    			conclusion:("thus"|"hence") (compact_statement|iterative_equality)|diffuse_conclusion
    			existential_assumption:"given" qualified_variables ["such" conditions] ";"
    			collective_assumption:"assume" conditions ";"
    			single_assumption:"assume" proposition ";"
    			assumption:single_assumption|collective_assumption|existential_assumption
    			generalization:"let" qualified_variables ["such" conditions] ";"
    			skeleton_item:generalization|assumption|conclusion|exemplification
    			reasoning_item:auxiliary_item|skeleton_item
    			suppose:"suppose" (proposition|conditions) ";" reasoning "end" ";"
    			suppose_list:suppose (suppose)*
    			case:"case" (proposition|conditions) ";" reasoning "end" ";"
    			case_list:case (case)*
    			reasoning:(reasoning_item)* [["then"] "per" "cases" simple_justification ";" (case_list|suppose_list)]
    			private_predicate_pattern:predicate_identifier "[" [type_expression_list] "]"
    			private_functor_pattern:functor_identifier "(" [type_expression_list] ")"
    			private_predicate_definition:"defpred" private_predicate_pattern "means" sentence ";"
    			private_functor_definition:"deffunc" private_functor_pattern "=" term_expression ";"
    			equating:variable_identifier "=" term_expression
    			equating_list:equating ("," equating)*
    			constant_definition:"set" equating_list ";"
    			private_definition:constant_definition|private_functor_definition|private_predicate_definition
    			auxiliary_item:statement|private_definition
    			functor_identifier:identifier
    			functor_segment:functor_identifier ("," functor_identifier)* "(" [type_expression_list] ")" specification
    			predicate_identifier:identifier
    			predicate_segment:predicate_identifier ("," predicate_identifier)* "[" [type_expression_list] "]"
    			scheme_segment:predicate_segment|functor_segment
    			scheme_premise:proposition
    			scheme_conclusion:sentence
    			scheme_parameters:scheme_segment ("," scheme_segment)*
    			scheme_identifier:identifier
    			scheme_block:"scheme" scheme_identifier "{" scheme_parameters "}" ":" scheme_conclusion ["provided" scheme_premise ("and" scheme_premise)*] ("proof"|";") reasoning "end"
    			scheme_item:scheme_block ";"
    			theorem:"theorem" compact_statement
    			correctness_condition:("existence"|"uniqueness"|"coherence"|"compatibility"|"consistency"|"reducibility") justification ";"
    			correctness_conditions:(correctness_condition)* ["correctness" justification ";"]
    			reduction_registration:"reduce" term_expression "to" term_expression ";" correctness_conditions
    			property_registration:"sethood" "of" type_expression justification ";"
    			identify_registration:"identify" functor_pattern "with" functor_pattern ["when" locus "=" locus ("," locus "=" locus)*] ";" correctness_conditions
    			functorial_registration:"cluster" term_expression "->" adjective_cluster ["for" type_expression] ";" correctness_conditions
    			conditional_registration:"cluster" adjective_cluster "->" adjective_cluster "for" type_expression ";" correctness_conditions
    			adjective:["non"] [adjective_arguments] attribute_symbol
    			adjective_cluster:(adjective)*
    			existential_registration:"cluster" adjective_cluster "for" type_expression ";" correctness_conditions
    			cluster_registration:existential_registration|conditional_registration|functorial_registration
    			attribute_loci:loci|"(" loci ")"
    			attribute_symbol:symbol
    			attribute_antonym:"antonym" attribute_pattern "for" attribute_pattern ";"
    			attribute_synonym:"synonym" attribute_pattern "for" attribute_pattern ";"
    			attribute_pattern:locus "is" [attribute_loci] attribute_symbol
    			attribute_definition:"attr" attribute_pattern "means" definiens ";" correctness_conditions
    			predicate_symbol:symbol|"="
    			predicate_antonym:"antonym" predicate_pattern "for" predicate_pattern ";"
    			predicate_synonym:"synonym" predicate_pattern "for" predicate_pattern ";"
    			predicate_property:("symmetry"|"asymmetry"|"connectedness"|"reflexivity"|"irreflexivity") justification ";"
    			predicate_pattern:[loci] predicate_symbol [loci]
    			predicate_definition:"pred" predicate_pattern ["means" definiens] ";" correctness_conditions (predicate_property)*
    			right_functor_bracket:symbol|"}"|"]"
    			left_functor_bracket:symbol|"{"|"["
    			functor_symbol:symbol
    			functor_loci:locus|"(" loci ")"
    			functor_synonym:"synonym" functor_pattern "for" functor_pattern ";"
    			functor_property:("commutativity"|"idempotence"|"involutiveness"|"projectivity") justification ";"
    			functor_pattern:[functor_loci] functor_symbol [functor_loci]|left_functor_bracket loci right_functor_bracket
    			functor_definition:"func" functor_pattern [specification] [("means"|"equals") definiens] ";" correctness_conditions (functor_property)*
    			mode_property:"sethood" justification ";"
    			partial_definiens:(sentence|term_expression) "if" sentence
    			partial_definiens_list:partial_definiens ("," partial_definiens)*
    			conditional_definiens:[":" label_identifier ":"] partial_definiens_list ["otherwise" (sentence|term_expression)]
    			label_identifier:identifier
    			simple_definiens:[":" label_identifier ":"] (sentence|term_expression)
    			definiens:simple_definiens|conditional_definiens
    			mode_synonym:"synonym" mode_pattern "for" mode_pattern ";"
    			mode_symbol:symbol|"set"
    			mode_pattern:mode_symbol ["of" loci]
    			mode_definition:"mode" mode_pattern ([specification] ["means" definiens] ";" correctness_conditions|"is" type_expression ";") (mode_property)*
    			specification:"->" type_expression
    			selector_symbol:symbol
    			field_segment:selector_symbol ("," selector_symbol)* specification
    			variable_identifier:identifier
    			locus:variable_identifier
    			fields:field_segment ("," field_segment)*
    			loci:locus ("," locus)*
    			structure_symbol:symbol
    			ancestors:structure_type_expression ("," structure_type_expression)*
    			structure_definition:"struct" ["(" ancestors ")"] structure_symbol ["over" loci] "(#" fields "#)" ";"
    			redefinition:"redefine" (mode_definition|functor_definition|predicate_definition|attribute_definition)
    			definition:structure_definition|mode_definition|functor_definition|predicate_definition|attribute_definition
    			permissive_assumption:assumption
    			loci_declaration:"let" qualified_variables ["such" conditions] ";"
    			notation_declaration:attribute_synonym|attribute_antonym|functor_synonym|mode_synonym|predicate_synonym|predicate_antonym
    			definition_item:loci_declaration|permissive_assumption|auxiliary_item
    			notation_block:"notation" (loci_declaration|notation_declaration)* "end"
    			registration_block:"registration" (loci_declaration|cluster_registration|identify_registration|property_registration|reduction_registration|auxiliary_item)* "end"
    			definitional_block:"definition" (definition_item|definition|redefinition)* "end"
    			notation_item:notation_block ";"
    			registration_item:registration_block ";"
    			definitional_item:definitional_block ";"
    			reserved_identifiers:identifier ("," identifier)*
    			reservation_segment:reserved_identifiers "for" type_expression
    			reservation:"reserve" reservation_segment ("," reservation_segment)* ";"
    			text_item:reservation|definitional_item|registration_item|notation_item|theorem|scheme_item|auxiliary_item
    			section:"begin" (text_item)*
    			text_proper:section (section)*
    			requirement:file_name
    			requirement_directive:"requirements" requirement ("," requirement)* ";"
    			article_name:file_name
    			library_directive:("notations"|"constructors"|"registrations"|"definitions"|"expansions"|"equalities"|"theorems"|"schemes") article_name ("," article_name)* ";"
    			vocabulary_name:file_name
    			vocabulary_directive:"vocabularies" vocabulary_name ("," vocabulary_name)* ";"
    			directive:vocabulary_directive|library_directive|requirement_directive
    			environment_declaration:"environ" (directive)*
    			article:environment_declaration text_proper
    
    			%import common.WS
    			%ignore WS
    		""", start='article')

Any help at all is appreciated!  I can try to make a shorter test input if you think it's necessary.  Thank you!

**Comment by erezsh** [comment]
Hi, I'm sorry but this is too big and disorganized for me to go deeply into it.

However, it's pretty clear why you got a recursion error. Your rule was:

    type_expression: adjective_cluster type_expression

And `adjective_cluster` was empty. Basically, when you have empty rules that can repeat forever, the parser will try to match them forever.

**Comment by MareoRaft** [comment]
Thanks.  It still hangs after eliminating the possibility of empty things being "zero or more".  I am going to close this issue anyway because it's too big.  I will build better tests and open new issues if I run into something, thanks.
