### ISSUE TITLE
Missing tag & release in github versus pypi

### ISSUE THREAD

**Issue by tigerfoot** [erezsh/lark#55]
As enhancement, It would be super cool to have tagged release here in conjunction with tgz release on pypi.
This can help to see changes happening between too release (There's no official changelog).

**Comment by erezsh** [comment]
Do you mean adding tags in git? Or is it a github feature?
It will be helpful if you can link to some guide describing this practice.

**Comment by nightblade9** [comment]
@erezsh I think what he's asking is: whenever you release a new version on PyPI, could you please also create a release on GitHub for your project?

- Browse to https://github.com/erezsh/lark
- Click Releases
- Click "Create a new Release"
- Fill out the info and save

As long as you do this after releasing on PyPI but before pushing any more commits, the release will automatically be tagged with the right commit. (If you pushed more commits first, I don't know the workflow, but I think GitHub allows you to pick the commit for the release.)

**Comment by tigerfoot** [comment]
@nightblade9 thanks that was I should have been written and expecting ...

**Comment by erezsh** [comment]
I created a new release for 0.5.1. Is it satisfactory?

**Comment by tigerfoot** [comment]
It is absolute perfection !!! \o/ thanks. 
closing
