### ISSUE TITLE
Lark can be made to submit an invalid lexer regex in e9603b5

### ISSUE THREAD

**Issue by chris-hexx** [erezsh/lark#56]
When I try to load the attached grammar 
[gplus3.lark.txt](https://github.com/erezsh/lark/files/1604642/gplus3.lark.txt) with LALR parsing and contextual lexing I get the stack trace [here](https://gist.github.com/chris-hexx/0378d37f63cd83a9c3afbaada213a9cd) .

I tracked this down to _create_unless(tokens) in lexer.py creating duplicate entries in the returned tokens, which turns into a regex with named groups with duplicate names and patterns. Turning delayed_strs into a set instead of a list seems to solve the issue and pass all tests it was passing without the change, at the cost of increased parser creation time. I don't know much about parsers or their internals, though, and less about how you'd like Lark structured.

Am I somehow abusing Lark, here, and should change my grammar or invocation? Is this actually a fix, or just a bandaid?

**Comment by erezsh** [comment]
Yes, this is a good fix! However, I pushed a slightly better one. Always a pleasure to solve a bug by removing code.
Thanks for the bug report!
