### ISSUE TITLE
Transformer isn't transforming output

### ISSUE THREAD

**Issue by nightblade9** [erezsh/lark#58]
Hi,

I have a modified version of your Python 3 example (Python 3 grammar, `python_parser` starter with an additional transformer) [here](https://github.com/nightblade9/dragon/tree/prototypes/prototypes/lark).

It seems like the transformer, although it correctly visits the nodes and prints something out, doesn't actually replace the value in the tree with the value I provide. (Or maybe it does, and the way I'm printing it out is causing problems.)

Can you please take a look and let me know where I'm going wrong?

Parser code:

```
        try:
            full_path = os.path.join(path, f)
            try:
                xrange
            except NameError:
                tree = python_parser3.parse(_read(full_path) + '\n')
                raw_tree = python_parser3.parse(_read(full_path) + '\n')
            else:
                tree = python_parser2.parse(_read(full_path) + '\n')
                raw_tree = python_parser2.parse(_read(full_path) + '\n')
            
            HaxeTransformer().transform(tree)
            convert_and_print(tree, full_path)    
```

Transformer code:

```
from lark import Transformer

class HaxeTransformer(Transformer):

    _LAST_NODE = None
    MARKER = "!!!"

    def import_stmt(self, node):
        HaxeTransformer._LAST_NODE = node

        output = "from "
        
        node = node[0].children # import_stmt => import_from
        package_name = node[0].children
        for child_node in package_name:
            output = "{}{}.".format(output, child_node.value)
        output = output[:-1] # trim last dot

        class_name = node[1].children[0].children[0].value
        output = "{} import {}".format(output, class_name)

        print("{} => {}".format(output, node))
        return output

    # def file_input(self, node):
    #     return HaxeTransformer.MARKER

    # def compound_stmt(self, node):
    #     return HaxeTransformer.MARKER

    # def funcdef(self, node):
    #     pass#return HaxeTransformer.MARKER

    # def funccall(self, node):
    #     return HaxeTransformer.MARKER
```

**Comment by erezsh** [comment]
Hi,
Transformers, as a rule, return a value instead of changing the tree in-place.
So I suspect that
    tree = HaxeTransformer().transform(tree)
Should resolve this issue.
If you only want to make in-place changes, you can use Visitor, which performs slightly better.

**Comment by nightblade9** [comment]
That seems to do it. Thanks for this.

Are there any examples of using Visitor?

**Comment by erezsh** [comment]
Lark uses it to process the grammar: https://github.com/erezsh/lark/blob/master/lark/load_grammar.py#L166

You can also read the implementation, it's only a dozen lines: https://github.com/erezsh/lark/blob/master/lark/tree.py#L149

**Comment by nightblade9** [comment]
Thanks for the visitor example. It looks like there's no real requirement per-se, just a `visit` method you can call however you like. That works for me.

**Comment by nightblade9** [comment]
I looked through the visitor source code and created a simple version that looks something like this:

```
from lark.tree import Visitor

class HaxeVisitor(Visitor):
    def process(self, tree):
        return self.visit(tree)
    
    def import_stmt(self, data):
        print("IMPORT {}".format(data))
    
    def compound_stmt(self, data):
        print("COMP".format(data))
```

This code looks exactly identical to the `Transformer` that I wrote above, down to the same method names (and probably implementations -- tree nodes look identical).

What exactly is the difference between a transformer and a visitor, and how do I choose which one to use? They look the same to me (create a subclass, write method names that correspond to the grammar rules, return tranformed output).

**Comment by erezsh** [comment]
The difference is between an in-place change (imperative approach) and returning copy (functional approach).
It's like the difference between `list.sort` and `sorted(list)`, both of which are orthogonal Python constructs.

**Comment by nightblade9** [comment]
That makes sense. I thought the differences would be bigger.

Thanks, I'll go with a visitor approach instead (seems more pythonic to me).

**Comment by nightblade9** [comment]
Just wanted to say thanks again for providing this library (and the examples). In basically a week, I got a simple Python file (hand-converted from a Haxe template) compiling and transpiling fully into virtually identical Haxe code. There were some bumps, but it wasn't as bad as I thought overall.

**Comment by erezsh** [comment]
Happy to hear it!

I aim to make Lark as user-friendly as possible. So if the bumps are related to Lark, I'd like to hear about them.

**Comment by nightblade9** [comment]
With Lark specifically, I didn't find documentation on what I wanted to know: the `.value` and `.children` parameters are really the main ones that I used to get the data I want and tranform.

The bigger hurdle for me was that I have a fully-formed Python grammar and a partial transformer; I ended up in situations where I needed to change a bunch of nodes at the same time, quickly (prototype style) or end up with runtime failures (can't convert tree/node into string in `",".join(...)`
