### ISSUE TITLE
LALR lexer behaves unexpected

### ISSUE THREAD

**Issue by Gentle** [erezsh/lark#59]
I'm trying to write a lalr grammar and am running into a problem:
I have the lexer fragment

```
BOOL_OP: "and" | "or" | "xor"
%import common.WORD
```

when I parse the input 'hello and world', the lexer uses (WORD, WORD, WORD) as token types, inlining seems to not work with lalr, how can I achieve that BOOL_OP gets precedence over WORD?

expected token types: (WORD, BOOL_OP, WORD)

**Comment by erezsh** [comment]
Lark can detect conflicts with simple strings and resolve them automatically, but BOOL_OP is an expression, and Lark can't detect it yet. (hopefully one day it will)

Meanwhile, the solution is to add priority to the terminal:

    BOOL_OP.2: "and" | "or" | "xor"

(or any number bigger than 1, which is the default priority)

**Comment by Gentle** [comment]
thank you, I misunderstood priorities to be lower number is higher priority, which is why I came to the wrong conclusion that adding priority numbers didn't work when actually I just gave wrong priorities :)
