### ISSUE TITLE
Limits of tree.InlineTransformer

### ISSUE THREAD

**Issue by DaRasch** [erezsh/lark#6]
I was toying around with lark, when I realized that certain things will break `InlineTransformer` and by extension `inline_args`.

Let's assume a simple example like this:
```python
import lark

grammar = lark.Lark('''
    hex_uint: HEX_UINT

    HEX_UINT: "0x" ("a".."f" | "A".."F" | "0".."9")+
''', start='hex_uint')

class Shaper(lark.InlineTransformer):
    def hex_uint(self, token):
        return int(token[2:], 16)

tree = grammar.parse('0x10Ff')
print(tree)
print(Shaper().transform(tree))
```
This will work fine. But if we replace `Shaper.hex_uint` with a class like so:
```python
class Integer(object):
    def __call__(self, token):
        return int(token[2:], 16)

class Shaper(lark.InlineTransformer):
    hex_uint = Integer()
```
it will break, because `utils.inline_args` assumes the callable to always be a function.

**Comment by erezsh** [comment]
Good catch. Sounds like a simple patch!

**Comment by DaRasch** [comment]
After some more poking around I think I understand the underlying problem. `utils.inline_args` works around pythons default binding behavior in class bodies, namely to treat function assignments as methods insteas of simple variable assignments. `tree.Transformer` actually still suffers from this problem, because it does not use `utils.inline_args`.

If I understood the problem correctly, I would recommend this as a possible solution:
```python
class Transformer(object):
    def _get_func(self, name):
        #return getattr(self.__class__, name) # for python3 this would be enough
        try:
            return self.__class__.__dict__[name]
        except KeyError as e:
            exc = e
        for base in self.__class__.__bases__:
            try:
                return base.__dict__[name]
            except KeyError:
                pass
        raise exc

    def _run_func(self, func, arglist):
        return func(arglist)

    def transform(self, tree):
        items = [self.transform(c) if isinstance(c, Tree) else c for c in tree.children]
        try:
            f = self._get_func(tree.data)
        except KeyError:
            return self.__default__(tree.data, items)
        else:
            return self._run_func(f, items)

    def __default__(self, data, children):
        return Tree(data, children)

class InlineTransformer(Transformer):
    def _run_func(self, func, arglist):
        return func(*arglist)
```
This completely bypasses pythons binding behavior and does not require any special case treatment as done in `utils.inline_args`.

There are two pitfalls to watch out for and document though:
```python
class Shaper(Transformer):
    def hex_uint(items):
        # Note no self parameter, as the class is only a namespace for us and we
        # ignore the binding
        return hex(items[0][2:], 16)

s = Shaper()
s.hex_uint = lambda items: int(items[0][2:], 16) # Will not work, as we work on
# the class __dict__ and ignore all instance variables
Shaper.hex_uint = lambda items: int(items[0][2:], 16) # Will work as expected
```
Both pitfalls obviously also apply for `tree.InlineTransformer`.

**Comment by erezsh** [comment]
Well, turns out the fix is much simpler, as you can see in commit e20b54b.

Of course, I just added a special case to inline_args, but it works, and doesn't rely on __dict__, so your pitfalls are not an issue. For example, this works:

    s = Shaper()
    s.hex_uint = lambda self, token: int(token[2:], 16)

Thanks for reporting this bug, I hope you find the fix satisfactory!
