### ISSUE TITLE
empty matches break xearley

### ISSUE THREAD

**Issue by night199uk** [erezsh/lark#63]
delayed_matches in the xearley scanner is indexed with the character number at which to unwind. 
```
                    delayed_matches[m.end()].append(item.advance(t))
```
Focus is on m.end (i.e. the last index of the match). If we match nothing (e.g. an optional or maybe match), the match is added to delayed_matches with index of the character we're currently on (i). Since the next set is built like this:
```
            next_set.add(delayed_matches[i+1])
```
i.e. the current character index plus one, an empty match is never correctly unwound from the delayed_matches stack and the scanner stalls. I suspect you may be able to do something better than I can as I'm mainly hacking away right now.

**Comment by erezsh** [comment]
Hi, can you provide an example grammar in which this problem occurs?

**Comment by night199uk** [comment]
Sure:

```
SPACE: " "
TAB: "\t"
TS: (TAB | SPACE)*
CR: "\r"
LF: "\n"
CRLF: CR LF
EOL: TS ( LF | CRLF )
ASCIICHARS: ("!" .. "~")

string:      ( TAB | SPACE | ASCIICHARS )+
comment:           TS "#" string EOL+
entry:             /[a-zA-Z_][a-zA-Z0-9_]*/
entries:           TS entry tail_comment
tail_comment:          ( TS [ "##" TS usage ] TS comment_or_eol ) | EOL
comment_or_eol:        comment | EOL
usage:             ( "MY_USAGE" | "OTHER_USAGE" )
start: entries*
```

Here is the test data:
```
  ConfigEntry ## MY_USAGE

```

This is a heavily abridged example from a (much) bigger grammar; so excuse any typos. There is some ambiguity here (# vs ##) which is understood, but I think the behaviour I'm getting right now is not as I would expect necessarily even forgiving the ambiguity.

**Comment by erezsh** [comment]
The problem is that Earley isn't supposed to deal with zero-with terminals (which are very different from empty rules). It might be possible to implement, but it will add a lot of complications. More importantly, it's not really necessary. 

Here's a version of your grammar that works:

    SPACE: " "
    TAB: "\t"
    TS: (TAB | SPACE)+
    CR: "\r"
    LF: "\n"
    CRLF: CR LF
    EOL: TS? ( LF | CRLF )
    ASCIICHARS: ("!" .. "~")

    string:      ( TAB | SPACE | ASCIICHARS )+
    comment:           TS? "#" string EOL+
    entry:             /[a-zA-Z_][a-zA-Z0-9_]*/
    entries:           TS? entry tail_comment
    tail_comment:          ( TS? [ "##" TS? usage ] TS? comment_or_eol ) | EOL
    comment_or_eol:        comment | EOL
    usage:             ( "MY_USAGE" | "OTHER_USAGE" )
    start: entries*

I added a validation before the parser runs, so future users won't be confused.

**Comment by night199uk** [comment]
Thanks. Makes sense; the error message helped me detect many other instances. There is still one challenge with this grammar I can't solve cleanly right now. Using your example above, notice that in the resulting tree, ## MY_USAGE is parsed as a comment with "# MY_USAGE".
```
    tail_comment
      comment_or_eol
        comment
           
          string	# MY_USAGE
```

I tried to raise the precedence of usage to resolve the ambiguity resulting from ## usage and # comment.
```
usage.2:             ( "MY_USAGE" | "OTHER_USAGE" )
```

However, this doesn't seem to help. Is the comment taking precedence because it is a longer match? Shouldn't optional matches further to the left take precedence?

**Comment by erezsh** [comment]
The parser is confused between a `tail_comment` (which starts with ##) and a regular `comment` that has # afterwards. Changing the priority in `usage` predictably has no effect on this.

What should solve this is to split `tail_comment` into two rules, and use priority to help the parser choose between them.
Another thing that might work is to use advanced regexps, and say the a `comment` # must not have another # following it. (I believe the syntax is (!?#), but you better check to make sure)

**Comment by night199uk** [comment]
Yes, I feared that might be the case. Unfortunately that breaks other cases, and I don't have control over the language spec or the source data I need to parse :-(

Here's the best I can come up with so far based on breaking it out into two rules, but it has another issue:
```
_TS: (" " | "\t")+
LF: "\n"
CRLF: "\r" "\n"
_EOL: _TS? ( LF | CRLF )
MY_USAGE: "MY_USAGE"
OTHER_USAGE: "OTHER_USAGE"

start: entries*
entries:           _TS? entry tail_comment
entry:             /[a-zA-Z_][a-zA-Z0-9_]*/
tail_comment:      comment_block | _EOL
comment_block:     usage? comment? _EOL
usage:             _TS? "##" _TS? ( MY_USAGE | OTHER_USAGE )
comment:           _TS? "#" _TS? _string
_string:           /[\t !-~]+/

```

These are the test cases I need to be able to parse:
```
ConfigEntry ## MY_USAGE
ConfigEntry # Just a comment
ConfigEntry ## MY_USAGE # And a comment
ConfigEntry ## INVALID_USAGE_DEFINITION - can be parsed as a comment
```

Essentially what I think I want is the grammar equivalent of a negative-lookahead to allow comments to only match when the 'usage' rule doesn't also match. Something like ?!usage. Is there any way around this?

**Comment by erezsh** [comment]
Taking this grammar you gave me, and just adding priority to usage, like:

    usage.2:             _TS? "##" _TS? ( MY_USAGE | OTHER_USAGE )

Provides the correct parse for all the examples, except that the last one is also accepted. You can then validate it manually in the tree, to see if `usage` is indeed correct or not.

Or, you can define `comment` thus:

    comment:           _TS? /#(?!#).*/

It parses everything correctly, and throws `UnexpectedInput` at the last one.

**Comment by night199uk** [comment]
Can you send the exact grammar you used to get that please? I'm getting different results for the 2nd example.
```
  entries
    entry	ConfigEntry
    tail_comment
      comment_block
        comment	# MY_USAGE # And a comment
```

**Comment by erezsh** [comment]
Here is my test code:

    from lark import Lark

    l = Lark(r"""
    _TS: (" " | "\t")+
    LF: "\n"
    CRLF: "\r" "\n"
    _EOL: _TS? ( LF | CRLF )
    MY_USAGE: "MY_USAGE"
    OTHER_USAGE: "OTHER_USAGE"

    start: entries*
    entries:           _TS? entry tail_comment
    entry:             /[a-zA-Z_][a-zA-Z0-9_]*/
    tail_comment:      comment_block | _EOL
    comment_block:     usage? comment? _EOL
    usage.2:             _TS? "##" _TS? ( MY_USAGE | OTHER_USAGE )
    comment:           _TS? /#(?!#).*/
    _string:           /[\t !-~]+/
    """)

    print(l.parse("ConfigEntry ## MY_USAGE\n").pretty())
    print(l.parse("ConfigEntry # Just a comment\n").pretty())
    print(l.parse("ConfigEntry ## MY_USAGE # And a comment\n").pretty())
    print(l.parse("ConfigEntry ## INVALID_USAGE_DEFINITION - can be parsed as a comment\n").pretty())
                                                    

And when running it:

**Comment by night199uk** [comment]
Okay, I think this is worked around with the regex hack :-)
