### ISSUE TITLE
Extending Grammar Without Changing Grammar File

### ISSUE THREAD

**Issue by nightblade9** [erezsh/lark#64]
Hi again,

You may recall that I'm using your Python 3 grammar (#57). I reached the point where I can transpile simple Python code into Haxe code (yay!)

The next problem I'm faced with is that Haxe contains certain constructs that don't exist in Python (or in the grammar); for example,  you need to specify the `override` keyword to override a method; and you can use the `@` notation for attributes (Python does have something similar, but less expressive).

I'm still hoping you'll decide to officially support and maintain the Python 3 grammar! In the meanwhile, what's the best way of adding these extensions to the parser, without changing the built-in grammar?  Right now, I'm [abusing long strings](https://github.com/nightblade9/dragon/commit/e9faf91dbecdd87ce3c4813341d5c2f56c219d2a) as comments to store my own syntax, but this seems wrong. (I tried doing the same thing with regular comments, but couldn't figure out how to modify the grammar to stop ignoring them and then get a generator to visit them.)

Is the right approach a two-step process (run it through two grammars, first mine then the Python one)? But if I do that, the Python stage will break because those tokens aren't valid Python code (eg. `override def function_name ...`

**Comment by erezsh** [comment]
>  reached the point where I can transpile simple Python code into Haxe code
Congrats!

So if I understand you correctly, you want to extend the Python language with constructs that don't exist in it?

**Comment by nightblade9** [comment]
> So if I understand you correctly, you want to extend the Python language with constructs that don't exist in it?

Yes, precisely. At the same time, I don't want to touch the grammar, so I'm abusing the long-strings feature to "hide" my custom syntax inside.

**Comment by erezsh** [comment]
That sounds like a bad idea. Why not adapt the existing grammar? Just make sure your changes are as clear and separate as possible, so that when I do update the grammar (once in a blue moon) it will only take you a few minutes to apply it.

Unless I make big structural changes to the grammar, in which case it's better that you have your own copy, or your code will break.

So either way, sounds to me like maintaining your own copy with clearly marked additions is the best way to go.

**Comment by nightblade9** [comment]
I really don't want to take ownership of maintaing/extending the Python grammar. It works much better for me if someone else maintains it and my changes are isolated.

Is there any way to do this without changing the Python 3 grammar?

**Comment by nightblade9** [comment]
I ended up (really struggling) finally changing the grammar file. This works well enough for me, I suppose.

**Comment by chamini2** [comment]
Hello!

I have a situation where we have two grammars, a normal one, and an extended version.

How could we achieve something like this for the extended:
```
%import base

%extend rule: /some_extension/
```

And the program will choose to use this grammar or the base depending on the situation?

**Comment by erezsh** [comment]
I think the easiest solution would be to have two Lark instances, once for each grammar. However, you can also use one instance, and choose between them by giving `start` to `Lark.parse()`
