### ISSUE TITLE
* doesn't accept 0 occurrences

### ISSUE THREAD

**Issue by DavidNemeskey** [erezsh/lark#66]
The following code:
```Python
p = Lark("""
    string : "'" STRING "'"
    STRING : ("a")*
""", start='string')
print(p.parse("''"))
```
raises `ParseError: Unexpected end of input! Expecting a terminal of: []`. 

`"a"?` also displays the same behavior. `"a"+`, on the other hand, raises `UnexpectedInput` (as expected).

Python 3.5, lark 0.5.2.

**Comment by erezsh** [comment]
This error is due to a lacking validation, and I actually fixed it two days ago (issue #63), but haven't made a release yet. If you use the latest `master` you'll get a proper error.

Briefly, Lark doesn't support zero-width terminals. So it's an error to define `STRING: "a"*`

I suggest you use:

    string : "'" STRING? "'"
    STRING : "a"+

**Comment by DavidNemeskey** [comment]
Thanks, that actually makes sense -- though an option to allow empty terminals (or at least a single ϵ) could be useful for certain types of grammars.

**Comment by erezsh** [comment]
In that case, it's possible to do the following:

    string : "'" string_inner "'"
    !string_inner : "a"*

It's less efficient and less convenient. But it will work.
