### ISSUE TITLE
Stream processing

### ISSUE THREAD

**Issue by DavidNemeskey** [erezsh/lark#67]
It would be great if lark had a function similar to `pyparsing`'s `scanString` (or `re`'s `finditer`): something which doesn't try to fit the pattern to the whole string, but iterates through all matches in it.

It would be even better if it could do it in a stream (iterator).

**Comment by erezsh** [comment]
Is this good enough?

    for i range(len(text)):
        lark_inst.parse(text[i:])

If not, then why not?

**Comment by erezsh** [comment]
Doing it for an iterator is impossible, because there's no way to know if the grammar will match until you've scanned the entire input.

**Comment by DavidNemeskey** [comment]
That solution would definitely not work, because I'd get `UnexpectedInput` if anything followed the pattern. Maybe if `Tree` told me the length of the match, I could do something similar:
```Python
i = 0
while i < len(text):
    try:
        tree = lark_inst.parse(tree[i:])
        i += len(tree)  # or whatever
    except lark.ParseError:
        i += 1
```
But since `parse` scans the entire input, it wouldn't work anyway.

**Comment by erezsh** [comment]
So the solution you're looking for doesn't allow overlapping matches?

And you're right, that will require a few changes to the parser. I believe it can be done, and it's probably not too difficult.

So in this feature, the parser will return the longest match? Or the first match?
