### ISSUE TITLE
Python 3 grammar interprets math brackets as tuples

### ISSUE THREAD

**Issue by nightblade9** [erezsh/lark#68]
Hi,

I'm using a slightly extended version of your [Python 3 grammar from samples](https://github.com/erezsh/lark/blob/master/examples/python3.g). Arithmetic operations seem okay, but it fails when I have brackets.

For example, if I try to parse the expression `1 + (2 * 3)`, it generates this tree:

```
  arith_expr
    number      1
    +
    tuple
      testlist_comp
        term
          number        2
          *
          number        3
```

Notice the use of `testlist_comp` and `tuple`.

I haven't finished writing transformer code for all the operations, but I think I would end up converting tuples to lists for my target language anyway.

Is this an issue with the grammar (or Lark's disambiguation) or is it something I can fix by writing some sort of code in my transformer class?

**Comment by erezsh** [comment]
Yes, it was an issue with the grammar. I pushed a fix.

**Comment by nightblade9** [comment]
That seems to work for me as well. Thanks for the prompt response.

Thanks for supporting the Python 3 grammar. That makes my life much, much easier :)
