### ISSUE TITLE
Create git tags for releases

### ISSUE THREAD

**Issue by timofurrer** [erezsh/lark#7]
Is it possible to push tags for the releases you make in PyPI? 

This helps a lot to keep track and see what's actually in a package. It's also pretty useful for mirroring repositories.

**Comment by erezsh** [comment]
Sure, I have no problem doing so.

What do you mean by mirroring repositories?

**Comment by timofurrer** [comment]
For example at the company I work we are usually vendoring third-party python dependencies and build them from source and host them in-house. If the tags are missing in the git repo it's hard to ensure that the builds we create match the PyPI builds.

**Comment by erezsh** [comment]
Ah, I see. I will begin doing so from now on.

Just curious, since I don't get a lot of feedback: Are you using Lark in your company or otherwise? And for what purpose?

It would help me decide where to take the library next.

**Comment by amirouche** [comment]
:-1:

**Comment by timofurrer** [comment]
@amirouche I texted @erezsh personally since I can't share any details - It's company work.

However, I really like Lark so far and I'm happy with it!
