### ISSUE TITLE
Fixed number of occurrences / repetition?

### ISSUE THREAD

**Issue by Diaoul** [erezsh/lark#75]
I've searched all the documentations but I cannot find any reference to a fixed number of occurrences. For example if I want to match a GUID, none of this work:
```
GUID: "{" 8*HEXDIG "-" 4*HEXDIG "-" 4*HEXDIG "-" 4*HEXDIG "-" 12*HEXDIG "}"
```
```
GUID: "{" HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG "-"
          HEXDIG HEXDIG HEXDIG HEXDIG "-"
          HEXDIG HEXDIG HEXDIG HEXDIG "-"
          HEXDIG HEXDIG HEXDIG HEXDIG "-"
          HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG HEXDIG "}"
```

What's the best way to create a GUID terminal?

**Comment by jkmacc-LANL** [comment]
Another example: "match between 3 and 5 string characters".  Would I need to write a regex, which means that I could use things in `common.g`?

**Comment by erezsh** [comment]
There is currently no syntax support for a limited range of occurrences. But I recognize the need for it, and I'll add it to the TODO list.

Meanwhile, you could use a regular expression in this case.

**Comment by erezsh** [comment]
Added support for latest `master` (not in the official release yet). Let me know if it works for you!
Here's how your code should look:

    GUID: "{" HEXDIG~8 "-" HEXDIG~8 "-" HEXDIG~8 "-" HEXDIG~4 "-" HEXDIG~12 "}"
