### ISSUE TITLE
unexpected token error

### ISSUE THREAD

**Issue by adibrastegarnia** [erezsh/lark#79]
I defined a simple grammar like this:
start: policy
        policy: OPERATION APP
        OPERATION: "Y" | "X"
        APP: "any"

Sample input: X any 

it gives me the following error: 

Unexpected token Token(WORD, u'X') at line 1, column 0.
Expected: ['policy', 'start', 'OPERATION']

Any suggestions?

**Comment by erezsh** [comment]
Well, you obviously forgot to provide a lot of detail.

For one, you're probably doing `%import common.WORD`, and you're also probably using the "standard" lexer instead of a dynamic one.

So, either remove the definition to `WORD`, use a dynamic lexer, or use priority to resolve it manually.

**Comment by adibrastegarnia** [comment]
Thanks Erez. I used parser='earley' and then the problem is fixed. Is it
the dynamic one?

Thanks,
Adib

**Comment by erezsh** [comment]
By default, parser="earley" uses the dynamic lexer, which means you don't have to worry about token collisions.
