### ISSUE TITLE
Read the docs build broken

### ISSUE THREAD

**Issue by wshayes** [erezsh/lark#8]

**Comment by erezsh** [comment]
Are you referring to http://lark-parser.readthedocs.io/en/latest/ ?

I was just playing around with it, and honestly I couldn't find any reason to use it, instead of just linking inside github..

**Comment by wshayes** [comment]
Yes - you may want to remove it if you aren't using it since I found it pretty easily using Google.

**Comment by erezsh** [comment]
Good point. Removed it, thanks!
