### ISSUE TITLE
Seemingly inconsistent parsing

### ISSUE THREAD

**Issue by adamdusty** [erezsh/lark#83]
I'm sure that this is probably an issue with my grammar, but I've been trying to figure this out for days now.

This snippet is part of a longer text file I am trying to parse:
```
360	"Initial setting", AsH3_9.line = off,
		RunHydride to 500,
		VentHydride to 100,
		RunMO1 to 19000,
		RunMO2 to 3500,
		VentMO to 4000,
		RunDopant to 4000,
		VentDopant to 1500,
		TMGa_1.press to 1000,
		TMAl_2.press to 1000,
		Sat1Rotation to 400,
		Sat2Rotation to [MFCflowSatA],
		Sat3Rotation to [MFCflowSatB], 
		Sat4Rotation to [MFCflowSatC],
		Sat5Rotation to [MFCflowSatD],
		Sat6Rotation to [MFCflowSatE],
		Sat7Rotation to [MFCflowSatF],
		Sat8Rotation to [MFCflowSatG],
		MainRot to 9,
		Ceiling.press to 1800,
		CeilingCtrl = open,
		Ceiling.inject to 1500,
		Ceiling.total to 2000,
		ViewportPurge to 100,
		CollectorPurge1 to 300,
		CollectorPurge2 to 300,
		HeaterPurge to 1000,
		LightPipePurge to 200,
                .
                .
                .
		CBr4_4.line = close,
		CBr4_4.run = off,
		CBr4_4.source to 28,
		CBr4_4.push to 450,
		CBr4_4.press to 500;
```

The two nearly identical lines:
```
CollectorPurge1 to 300,
CollectorPurge2 to 300,
```

produce two different outcomes when I print the tree.
```
    lin_ramp
      name	CollectorPurge1
      number	300
    lin_ramp
      name	Collec
      name	r
    lin_ramp
      name	Purge2
      number	300
```

The BNF grammar is given to me, but incomplete, so I'm trying to piece it all together. I've been most focused on what seems to be overlap between the lin_ramp rule and the name terminal.
```
?start: statement+

string: ESCAPED_STRING
number: SIGNED_NUMBER
name: /[_A-z]([\._A-z0-9])*/
?device_name: name //| (name /\./ name)
?device_list: device_name+
?digital_const: /on|off|open|close/

?stmt_list: statement+
variable_stmt   : ("variable"|"parameter") name "=" expression ";" -> variable
timed_stmt      : expression string? action_list ";"
macro_stmt      : name ";" | name "{" stmt_list "}"
conditional_stmt: (string? action_list ",")? "until" device_name /<<|==|>>/ expression ";"
loop_stmt       : "loop" expression "{" stmt_list "}"
                | "loop" expression name ";"
read_stmt       : "read" name ";"

?statement   : variable_stmt
            | timed_stmt
            | macro_stmt
            | conditional_stmt
            | loop_stmt
            | read_stmt

?expression : number
            | digital_const
            | "(" expression ")"
            | "-" expression
            | expression operator expression
            | function "(" expression ")"
            | "[" expression "]"
            | device_name

function    : "sin"
            | "cos"
            | "tan"
            | "exp"
            | "exp10"
            | "log"
            | "log10"
            | "sqrt"

operator    : /\+/
            | /\-/
            | /\*/
            | /\//
            | /\%/
            | /\^/

action_list: ([","] action)*
?action  : set_val
        | follow
        | lin_ramp
        | nonlin_ramp
        | group
        | stats
        | data_log

set_val     : device_name digital_const
            | name "=" expression
            | device_name "=" expression
follow      : device_name "follow" expression
lin_ramp    : device_name "to" expression// ["in" expression]
nonlin_ramp : device_name "with" expression ["in" expression]
group       : name "=" (device_name|name)+ ";"
stats       : /begin|end/ "stat" device_list
data_log    : "dlog" (expression|/off/)





COMMENT: /#[^\n]*/
WS: /[ \t\f\r\n]/+

%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%ignore COMMENT
%ignore WS
```

**Comment by adamdusty** [comment]
#81 I also sometimes experience this issue, where I get different output often, which makes me assume the issue is in my grammar file.
```
    lin_ramp
      name	Collec
      name	r
    lin_ramp
      name	Purge1
      number	300
    lin_ramp
      name	CollectorPurge2
      number	300
```

**Comment by erezsh** [comment]
Yes, and no. It certainly is an issue with Lark that the parse isn't always consistent, and it's on my TODO list to fix it, but at the same time, there are countless ways to solve this in your grammar.

For example, you make the comma required, so it can't split lin_ramp in the middle:

    action_list: ("," action)*

Or you can require whitespace around "to":

    lin_ramp    : device_name " to " expression// ["in" expression]

And surprisingly enough, it seems that your grammar can work with a standard lexer, which is faster and guaranteed to be consistent:

   parser = Lark(g, lexer="standard")

Each of these approaches has pros and cons, regarding which inputs they accept and which they don't, so it's up to you to decide which way you'll go.

**Comment by adamdusty** [comment]
Thank you. I tested both the required comma and the " to " solutions, and they both seemed to work. The files I'm parsing are 1000+ lines long, so its hard to tell if everything is working as intended, but both look good as far as I can tell.

I tried using the standard lexer, but I ran into some other problems parsing `"[" expression "]"`. I don't really know what I'm doing, so I don't know the difference between the standard and dynamic lexers. How can you tell whether or not it works with the standard lexer, just try and see?

Anyway, thanks a ton. Lark has been by far the easiest parsing library to work with that I've found.

**Comment by erezsh** [comment]
There's a lot of theory behind it, but to put it briefly:

The standard lexer is a preprocessor. It does a separate pass on the input to extract the tokens, based on a simple set of rules (match tokens one after the other, always choosing the first viable match, a bit like PEG parsers). However, that can lead to wrong tokenisation if there is any nondeterminism in the grammar.

The dynamic lexer, which is a unique invention and exists only in Lark (to the best of my knowledge), is a subroutine of the parser. It guarantees that every combination will be tried on the road to a correct parse. The downsides is that it's slower, because it has to try many combinations, and that I still haven't worked out all the kinks for the common use case :)

Anyway, I'm glad that my solutions were good enough for now. Feel free to ask more questions if you get stuck. And thank you for the compliment! That's what gives me the motivation to keep improving it.
