### ISSUE TITLE
SIGNED_FLOAT common grammar seems incorrect

### ISSUE THREAD

**Issue by achedeuzot** [erezsh/lark#84]
Hello Erez,

I'm using your excellent `lark` library and I use some floats. I was importing `SIGNED_FLOAT` form the `common.g` grammar and I noticed that the `SIGNED_FLOAT` looks incorrect:

    SIGNED_FLOAT: ["+"|"-"] INT 

shouldn't it be 

    SIGNED_FLOAT: ["+"|"-"] FLOAT

Thanks again !

**Comment by erezsh** [comment]
Yes, you're absolutely correct! It's an oversight on my part.

**Comment by erezsh** [comment]
Fixed, thanks!
