### ISSUE TITLE
Token and Derivation get compared somehow

### ISSUE THREAD

**Issue by chris-hexx** [erezsh/lark#91]
Trying to parse 
'$u_delta < 1.5 and $u_i < $u_elements'
, without single quotes, using this Lark invocation:
self.expr_parser = Lark(open("gplus_expr.lark.txt").read(), start='expr')
and the attached grammar [gplus_expr.lark.txt](https://github.com/erezsh/lark/files/1744626/gplus_expr.lark.txt)
yields the attached stack trace. [trace.txt](https://github.com/erezsh/lark/files/1744627/trace.txt)

Wrapping a try/catch around the implementation of compare in lark/lark/utils.py seems to work, as in 
```
    def compare(a, b):
        try:
            if a == b:
                return 0
            elif a > b:
                return 1
            else:
                return -1
        except TypeError:
            return 0
```
and results in no failing tests, but this seems very unprincipled.

**Comment by erezsh** [comment]
Fixed in `master`.

Btw, you should probably make `dsvar_name` and `uservar` into tokens (`USERVAR` etc.) to get their strings in the tree instead of lists of characters.

**Comment by chris-hexx** [comment]
Oh, that's what was doing that? Thanks!
