### ISSUE TITLE
LALR(1) parser exhibits non-linear parse time with high line count files

### ISSUE THREAD

**Issue by psboyce** [erezsh/lark#94]
Background: For my work I developed a bytecode compiler for a language called Serial Vector Format, (SVF) it's an industry standard language used for describing how to configure FPGAs. In this case I needed to configure FPGAs directly from an embedded microprocessor with limited memory, something that SVF is ill-suited for. I developed a bytecode form of SVF that requires 64 bytes of memory and is streamable (no backtracking required) and I used Lark to parse the SVF and compile it into bytecode.

Problem: I've noticed that the compile time with lark's LALR parser is non-linear; with PyPy an 80k SVF file took 16 seconds to compile while a 240k line file took 120 seconds, a roughly 8 fold increase.

Since I can't share the tool or the SVF configuration file because they're proprietary I developed a simplified language in my spare time that shares some of the most prominent grammatical features of SVF. It's purely a toy language; it's not useful for anything as far as I'm aware, hence I've dubbed it clishmaclaver.

It uses LALR for parsing, includes a transformer that reduces the parse tree to bytearrays and includes a tool for generating random lines of clishmaclaver. I generated files with 50k, 100k and 150k lines and parsed them multiple times to compose a benchmark. PyPy was used with all these runs.

| Line count | Run Count  | Average Time (seconds) | Multiple of baseline (50k lines) |
|------------|------------|------------------------|----------------------------------|
| 50,000 | 10 | 21.760 | 1 |
| 100,000 | 5 | 88.277 | 4.057 |
| 150,000 | 5 | 188.334 | 8.655 |

Attached are three files, for best results use a POSIX compliant OS like Linux or OS X.

1. "clish_gen.py" is a script for generating clishmaclaver files and takes a line count as an argument. Either redirect the output to a file or flood your terminal with useless, but well structured, ASCII text.

2. "clishmaclaver.g" is the grammar for clishmaclaver. If you have a copy of the SVF specification for reference it's modeled after the HDR/HIR/TDR/TIR/SDR/SIR statements.

3. "clishmaclaver.py" is a script for parsing and compiling clishmaclaver. It takes two arguments, an input file and an output file. Its output isn't very useful so /dev/null will suffice for the second argument.

I suspect the issue has something to do with the grammar but I'm not a grammar expert.

[clishmaclaver.zip](https://github.com/erezsh/lark/files/1756842/clishmaclaver.zip)

**Comment by erezsh** [comment]
Okay, so I've identified two major points causing non-linear performance in tree construction (One of which is relevant even in tree-less code).

Here's a short explanation, in case you're curious: Lark implements loops using recursion, so when you write `rule*` it rewrites it as a recursive rule, and then merges the recursive tree structure into a Python list. But, it does so recursively, which means it ran this line again and again:

    filtered += children[i].children

So essentially it kept copying the elements around, performing `O(n^2)` operations. All in all, pretty embarrassing for me, so thanks for reporting this issue!

Anyway, it's solved now, and pushed to `master`. And when running your tests, it seems that performance is now truly linear.

Give it a spin :)

**Comment by psboyce** [comment]
Looks much better! Pypy parses 150k lines in about 5 seconds now, that's an incredible speed boost. Thanks for taking a look at this!

**Comment by eddieschoute** [comment]
@erezsh Would you mind doing a minor release on pypi for this fix? I also need to speed boost and it being on pypi simplifies things.

**Comment by erezsh** [comment]
Done, released as 0.5.5
